/*
 Oracle Infinity
 @preserve Copyright (c) 2017, 2018, 2019, Oracle and/or its affiliates. All rights reserved.
 analytics.js v1.0
 Created: 2023-11-14T12:16:27+0000

*/
(function(k,a){if(!k.ORA.analytics){var b=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_PRODUCT_READY,ORA.Event.STATUS_SUCCESS));ORA.common.TrackingPipeline.productIsReady("analytics");ORA.Debug.debug("setProductReady()","ANA")};ORA.analytics={dcsRef:null,plugins:{},addEventListener:ORA.addDOMEvent,eventQueue:null,version:{major:1,minor:0,inc:4},versionStr:"1.0.4",qryparams:{},dcsdelay:25,productReadyLatch:{},isSeedMessageTriggered:!1,elemOfEvent:function(c,d){var f=c.target||c.srcElement,
q=d||{};"string"===typeof d&&(q={},q[d.toUpperCase()]=1);for(;f&&f.tagName&&!q[f.tagName.toUpperCase()];)f=f.parentElement||f.parentNode;return f},multiTrack:function(c){try{return ORA.analytics.dcsRef.dcsMultiTrack(c),!1}catch(d){throw ORA.Debug.error("Error ORA.analytics.multiTrack: "+d.toSource(),"ANA"),d;}},instantiateExternal:function(){ORA.analytics.qryparams=ORA.common.QueryParamCache.getCache();ORA.analytics.loadJS=ORA.common.loadJS;ORA.analytics.eventQueue=new ORA.common.Queue;ORA.analytics.prettify=
ORA.common.JSONPrettify;ORA.analytics.dcsSaveCookie=ORA.common._setCookie;ORA.analytics.dcsDeleteCookie=ORA.common._deleteCookie;ORA.analytics.extendArray=ORA.common.extendArray;ORA.analytics.isFn=ORA.common.isFn;ORA.analytics.isArray=ORA.common.isArray;ORA.analytics.getCookieAsObj=ORA.common._getCookieAsObj;ORA.analytics.isEmpty=ORA.common.isEmpty;ORA.analytics.click=ORA.click;ORA.analytics.view=ORA.view;ORA.analytics.collect=ORA.collect;ORA.analytics.regPlugin=ORA.regPlugin;ORA.analytics.getTagId=
ORA.getTagId;ORA.analytics.getContextName=ORA.getContextName;ORA.analytics.getPluginsConfig=ORA.analytics._getPluginsConfig;ORA.analytics.setCookie=ORA.common._setCookie;ORA.analytics.deleteCookie=ORA.common._deleteCookie;ORA.analytics.getCookieRaw=ORA.common._getCookieRaw;ORA.analytics.getIEVer=ORA.common._getIEVer;ORA.analytics.isOptedOut=ORA.common._isOptedOut;ORA.analytics.setInfinityOptOut=ORA.common._setInfinityOptOut;ORA.analytics.addMutation=ORA.analytics.addMutation;ORA.analytics.rmMutation=
ORA.analytics.rmMutation;ORA.analytics.getFPC=function(){var c=ORA.analytics.getCookieAsObj(ORA.analytics.dcsRef.FPCConfig.name);return c&&c.id?c.id:null}},reset:function(){ORA.Debug.info("Analytics reset()","ANA");ORA.analytics.dscRef={}},execute:function(c){ORA.Debug.info("Analytics execute()","ANA");ORA.analytics.reset();var d=ORA.analyticsModule.prototype.oraConfigObj;c&&c.params&&ORA.hasVal(c.params)?(c=ORA.common.getMergedConfigs(d,c.params),ORA.analytics.setup(c)):ORA.analytics.setup(d)},performView:function(){ORA.common.clientID.isWaitForSetClientId&&
ORA.common.clientID.isClientIdSet&&(ORA.addEventHandler(ORA.Event.ANA_PRODUCT_READY,ORA.view()),ORA.common.clientID.isWaitForSetClientId=!1)},registerLoaderEvents:function(){ORA.addEventHandler(ORA.Event.LOADER_RESET,this.reset);ORA.addEventHandler(ORA.Event.LOADER_EXECUTE,this.execute);ORA.common.clientID.isClientIdSet?this.performView():ORA.addEventHandler(ORA.Event.SET_CLIENT_ID,this.performView)},setupPluginMgr:function(c){var d=ORA.analytics.getPluginCount("ora-plugins"),f=ORA.common.pluginMgr,
q=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_ORA_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("setupPluginMgr - ora Plugins Initialized, productReadyLatch.countDown()","ANA");ORA.analytics.productReadyLatch.countDown()};0<d?(ORA.Debug.debug("setupPluginMgr - ora pluginCount("+d+"), deferring initPluginsCallback until plugins loaded","ANA"),f.setNumExpectedPlugins(d),f.setInitPluginsCallback(q),f.setInjectConfigsCb(ORA.analytics._getPluginsConfig,"ora-plugins")):(0===d&&c.waitForGetClientIDCallback.apply(c)?
(ORA.Debug.debug("setupPluginMgr - ora pluginCount("+d+"), now waiting on getId, so wait to countDown latch ","ANA"),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_ORA_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS))):ORA.Debug.debug("setupPluginMgr - ora pluginCount("+d+"), not waiting on getId so countDown immediately","ANA"),q());f.setReady();ORA.fireEvent(new ORA.Event(ORA.Event.COMMON_ORA_PLUGINMGR_READY,ORA.Event.STATUS_SUCCESS));f=ORA.analytics.getPluginCount("hosted-plugins");var u=ORA.common.hostedPluginMgr,
w=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_HOSTED_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("setupPluginMgr - Hosted Plugins Initialized, productReadyLatch.countDown()","ANA");ORA.analytics.productReadyLatch.countDown()};0<f?(ORA.Debug.debug("setupPluginMgr - Hosted pluginCount("+f+"), deferring initPluginsCallback until plugins loaded","ANA"),u.setNumExpectedPlugins(f),u.setInitPluginsCallback(w),u.setInjectConfigsCb(ORA.analytics._getPluginsConfig),u.processHostedPlugins(c.config["hosted-plugins"])):
0===f&&c.waitForGetClientIDCallback.apply(c)?(ORA.Debug.debug("setupPluginMgr - hosted pluginCount("+d+"), now waiting on getId, so wait to countDown latch ","ANA"),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_HOSTED_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS)),q()):(ORA.Debug.debug("setupPluginMgr - Hosted pluginCount("+d+"), not waiting on getId so countDown immediately","ANA"),w());u.setReady();ORA.fireEvent(new ORA.Event(ORA.Event.COMMON_HOSTED_PLUGINMGR_READY,ORA.Event.STATUS_SUCCESS))},setupProductCountdownLatch:function(c){var d=
2;c.waitForGetClientIDCallback.apply(c)&&(ORA.Debug.trace("prodCountdownLatch: waitForGetIdCall, latchCount++","ANA"),d++);ORA.analytics.productReadyLatch=new ORA.common.CountDownLatchClass(d,b,"ProductReadyLatch");ORA.Debug.debug("set productReadyLatch to "+d,"ANA")},setCheckSetDisableSeed:function(c){!0===c.s_disableSeed&&ORA.common.TrackingPipeline.disableSeed()},setWaitForSetClientId:function(c){!0===c.s_waitForSetClientId&&ORA.common.clientID.waitForSetClientId()},setup:function(c){try{ORA.Debug.debug("Analytics setup() started",
"ANA");this.instantiateExternal();this.setCheckSetDisableSeed(c);this.setWaitForSetClientId(c);var d=new ORA.analytics.dcs;d.init(c);this.setupProductCountdownLatch(d);d.setup();this.dcsRef=d;this.setupPluginMgr(this.dcsRef);this.registerLoaderEvents();ORA.fireEvent(new ORA.Event(ORA.Event.ANA_SETUP_COMPLETE,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("Analytics setup() has finished","ANA")}catch(f){ORA.Debug.error("Analytics setup() failure",201,f,"ANA")}},addMutation:function(c,d,f){return ORA.common.TrackingPipeline.registerMutation(c,
d,f?f:2)},rmMutation:function(c){return ORA.common.TrackingPipeline.deregisterMutation(c)},getProductTimeout:function(){return ORA.common.TrackingPipeline.getProduct("analytics").timeout},_getPluginsConfig:function(c,d){var f={};ORA.analyticsModule.prototype.oraConfigObj[d]&&ORA.analyticsModule.prototype.oraConfigObj[d][c]&&(f=ORA.analyticsModule.prototype.oraConfigObj[d][c]);return f},getPluginCount:function(c){return ORA.analyticsModule.prototype.oraConfigObj[c]?ORA.common.extendObject(ORA.analyticsModule.prototype.oraConfigObj[c]).length():
0},getConfigParams:function(){var c=ORA.analytics,d={},f=ORA.analytics.dcsRef;f&&ORA.common.extendArray(["accountGuid","destinations","enabled","i18n","timezone"]).forEach(function(q){f[q]&&(d[q]=f[q])});d.version=c.version;d.versionStr=[d.version.major,d.version.minor,d.version.inc].join(".");d.dcsdelay=c.dcsdelay;return d},getEndPoint:function(){return"https://"+ORA.analytics.dcsRef.destinations[0].collectionServer+"/v3/"+ORA.analytics.dcsRef.destinations[0].accountGuid}};ORA.Debug.debug("ORA.analytics instantiation success",
"ANA")}})(window,window.document);
(function(k,a){ORA.analytics.dcs=function(){var b=k.RegExp?RegExp("dcs(uri)|(ref)|(aut)|(met)|(sta)|(sip)|(pro)|(byt)|(dat)|(p3p)|(cfg)|(redirect)|(cip)","i"):"";this.exre=b;this.re={};this.plugins=this.plugins={};this.trackingData=this.trackingData={};this.DCS=this.DCS={};this.destinations=[];this.DCSext=this.DCSext={};this.errors=this.errors=[];this.FPCConfig=this.FPCConfig={};this._onsitedoms=[];this.gTempWtId=this.gWtAccountRollup=this.oraId="";this.prettify=ORA.analytics.prettify;return this};
ORA.analytics.dcs.prototype={init:function(b){var c=b;try{ORA.Debug.debug("dcs init() start","ANA");"undefined"===typeof c&&(c={});this.config=c;var d=this;b=function(w,v){return c.hasOwnProperty(w)?c[w]:v};var f=function(w,v,r){return w?w.hasOwnProperty(v)?w[v]:r:r};this.extendArray=ORA.common.extendArray;this.errorlogger=function(w){ORA.Debug.error("Dcs",100,w,"ANA")};c.defaultCollectionServer||ORA.Debug.error("dcs init:  missing defaultCollectionServer");this.destinations=this.destinations=function(w){if(!w||
0===w.length)throw Error("Destinations are not configured");for(var v=[],r=0;r<w.length;r++){var e=f(w[r],"collectionServer",c.defaultCollectionServer),m={};m.collectionServer=m.collectionServer=e;m.timeout=m.timeout=f(w[r],"timeout",2E3);m.accountGuid=m.accountGuid=w[r].accountGuid;m.endpoint=m.endpoint=d.collectionEndpoint(e,w[r].accountGuid);v.push(m)}return v}(c.destinations);this.accountGuid=this.accountGuid=this.destinations[0].accountGuid;this.queue=this.queue=b("queue",[]);this.wtidTimeout=
b("wtidTimeout",1E3);this.timezone=this.timezone=b("timezone",-8);this.enabled=this.enabled=b("enabled",!0);this.i18n=this.i18n=b("i18n",!1);this.re=k.RegExp?d.i18n?{"%25":/%/g,"%26":/&/g,"%23":/#/g}:{"%25":/%/g,"%09":/\t/g,"%20":/\x20|\xA0|\x7F/g,"%23":/#/g,"%26":/&/g,"%2B":/\+/g,"%3F":/\?/g,"%5C":/\\/g,"%22":/"/g}:"";if(c.metanames){var q=c.metanames.toLowerCase();this.metanames=ORA.common.extendArray(q.split(","))}if(!0===c.metatagAuto||"true"===c.metatagAuto)this.metatagAuto=!0;this.skip_qp_no_value=
this.skip_qp_no_value=b("skip_qp_no_value",!1);this.skip_qp_no_equals=this.skip_qp_no_equals=b("skip_qp_no_equals",!1);this.skip_qp=this.skip_qp=b("skip_qp",!1);this.paidsearchparams=b("paidsearchparams","gclid");ORA.analytics.dcsdelay=c.dcsdelay||ORA.analytics.dcsdelay;this.delayAll=this.delayAll=b("delayAll",!1);this.preserve=this.preserve=b("preserve",!0);this._onsitedoms=b("onsitedoms","");ORA.common.isFn(this._onsitedoms.test)||(this._onsitedoms=ORA.common.extendArray(this._onsitedoms.toLowerCase().split(",")),
this._onsitedoms.forEach(function(w,v,r){r[v]=w.replace(/^\s*/,"").replace(/\s*$/,"")}));b("adimpressions",!1)&&(this.adclickparam=b("adsparam","WT.ac"));this.FPCConfig.enabled=this.FPCConfig.enabled=f(c.FPCConfig,"enabled",!0);this.FPCConfig.domain=this.FPCConfig.domain=f(c.FPCConfig,"domain","");this.FPCConfig.name=this.FPCConfig.name=f(c.FPCConfig,"name","ORA_FPC");this.FPCConfig.optOutCName=this.FPCConfig.optOutCName=f(c.FPCConfig,"optOutCName","Infinity.optout");this.FPCConfig.legacyCName=this.FPCConfig.legacyCName=
f(c.FPCConfig,"legacyCName","WT_FPC");this.FPCConfig.expiry=this.FPCConfig.expiry=f(c.FPCConfig,"expires",63113851500);63113851500<this.FPCConfig.expiry&&(this.FPCConfig.expiry=63113851500);this.FPCConfig.expireDate=new Date(this.getTime()+this.FPCConfig.expiry);this.FPCConfig.sessionOnly=0===this.FPCConfig.expiry||f(c.FPCConfig,"sessionOnly",!1);this.FPCConfig.autoTLD=this.FPCConfig.autoTLD=f(c.FPCConfig,"autoTLD",!1);c.cookieTypes&&(this.FPCConfig.enabled="none"!==c.cookieTypes.toLowerCase());var u=
{DNTBehavior:ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT",wtidTimeout:this.wtidTimeout,cookie:{enable:this.FPCConfig.enabled,name:this.FPCConfig.name,expires:this.FPCConfig.expiry,autoTLD:this.FPCConfig.autoTLD,sessionOnly:this.FPCConfig.sessionOnly,expireDate:this.FPCConfig.expireDate,domain:this.FPCConfig.domain},endpoint:{clientIDServer:this.destinations[0].collectionServer,accountGuid:this.destinations[0].accountGuid,protocol:"https"}};ORA.common.clientID.clientId=
this.dcsGetFPC().id||null;ORA.common.clientID.setConfig(u);this.plugins=c.plugins||{};ORA.analytics.dcs.prototype.action_collect=ORA.analytics.dcs.prototype.action_collect;ORA.analytics.dcs.prototype.init=ORA.analytics.dcs.prototype.init;ORA.analytics.dcs.prototype.setup=ORA.analytics.dcs.prototype.setup;ORA.analytics.dcs.prototype.dcsGetFPC=ORA.analytics.dcs.prototype.dcsGetFPC;ORA.analytics.dcs.prototype.dcsGetCookie=ORA.analytics.dcs.prototype.dcsGetCookie;ORA.analytics.dcs.prototype.dcsNavigation=
ORA.analytics.dcs.prototype.dcsNavigation;this.registerProtocol();ORA.Debug.debug("dcs init() finish","ANA");return this}catch(w){throw ORA.Debug.error("Error in init() - "+w.toString()),w;}},registerProtocol:function(){var b=ORA.common.TrackingPipeline;null===b.getCommProtocol(ORA.common.CommManager.GIF)&&(ORA.common._analyticsProtocol=ORA.common.protocols.gifProtocol,b.setCommProtocol(ORA.common.CommManager.GIF,ORA.common._analyticsProtocol))},collectionEndpoint:function(b,c,d){b||ORA.Debug.debug("Warning:  missing collectServer");
b=b?b:"";if(!c)throw Error("accountGuid must be configured for "+b);return"https://"+b+"/"+c+"/"+(d?d:"dcs.gif")},setReady:function(){ORA.Debug.debug("setReady()","ANA");this._readySet||(this.flushqueue(),this.redirectqueue(),this._readySet=!0)},flushqueue:function(){ORA.Debug.trace("flushqueue()","ANA");for(var b=0;b<this.queue.length;b++)this.doAction(this.queue[b]);this.queue=[]},redirectqueue:function(){var b=this;this.queue.push=function(c){b.doAction(c)}},dcsGetCookie:function(b){return ORA.analytics.dcsGetCookie(b,
this.FPCConfig.name)},dcsIsFpcSet:function(b,c){var d=ORA.analytics.getCookieAsObj,f=ORA.analytics.isEmpty;d=d(b);this.gTempWtId=d.id;return f(d)?2:c===d.id?0:3},dcsGetFPC:function(){return ORA.analytics.getCookieAsObj(this.FPCConfig.name)},dcsFPC:function(){var b=ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT";if(!ORA.analytics.isOptedOut())if(this.FPCConfig.enabled){this.trackingData.ce="1";var c=this.trackingData,d=this.FPCConfig.name,f=new Date,q=6E4*f.getTimezoneOffset()+
36E5*this.timezone;f.setTime(f.getTime()+q);var u=new Date(f.getTime());c.co_f="";c.vtvs=c.vt_f="";var w=ORA.analytics.getCookieAsObj(d);q=function(r){var e=w.id;null!==e&&(c.co_f=e,f.getTime()>u.getTime()+288E5&&u.setTime(f.getTime()),"undefined"===typeof r.gTempWtId||r.gTempWtId!==e)&&(c.vt_f="1",r.gTempWtId=e)};if(!ORA.common._isDNTSet()||"honorDNT"!==b){q(this);c.co_f=escape(c.co_f);w.id=c.co_f;this.FPCConfig.sessionOnly?ORA.common.mobile.nativeAppCkSend({name:d,value:w,domain:this.FPCConfig.domain,
date:this.FPCConfig.expireDate,path:"/",type:"session",timeout:this.FPCConfig.expiry}):ORA.common.mobile.nativeAppCkSend({name:d,value:w,domain:this.FPCConfig.domain,date:this.FPCConfig.expireDate,path:"/",type:"persisted",timeout:this.FPCConfig.expiry});b=ORA.common.isFpcSet(d,c.co_f);0!==b&&(c.co_f="",c.vt_f=b);var v={};ORA.common.extendObject(c).forEach(function(r,e){null!==r&&""!==r&&(v["WT."+e]=r)});return v}}else this.trackingData.ce="0"},dcsGetIdCallback:function(b){"undefined"!==typeof b&&
(this.oraId||(this.oraId=b),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_GETID,ORA.Event.STATUS_SUCCESS)));this.setReady();ORA.analytics.productReadyLatch.countDown()},waitForGetClientIDCallback:function(){var b=ORA.common._getCookieAsObj(),c=2!==this.dcsIsFpcSet(this.FPCConfig.name),d=ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT";d=ORA.common._isDNTSet()&&"honorDNT"===d;return ORA.common._isOptedOut(b)||c||!this.FPCConfig.enabled||d||ORA.common._getConfigObject().s_waitForSetClientId?
!1:!0},setup:function(){try{var b=this,c=function(d){b.dcsGetIdCallback.apply(b,[d])};this.FPCConfig.enabled?ORA.common.mobile.delay(function(){b.waitForGetClientIDCallback.apply(b)?ORA.common.clientID.getClientID(c):(ORA.common.clientID.getId(ORA.common.clientID.cfg.endpoint,null),b.setReady.apply(b,[]))},"ANA",ORA.analyticsModule.prototype.oraConfigObj):this.setReady();this.enQueue("collect",{element:void 0,event:void 0});ORA.fireEvent(new ORA.Event(ORA.Event.ANA_DCS_SETUP,ORA.Event.STATUS_SUCCESS));
ORA.addEventHandler(ORA.Event.SET_CLIENT_ID,function(d){b.oraId=d.params},null,!0);ORA.addEventHandler(ORA.Event.CLEAR_CLIENT_ID,function(){ORA.analytics.pageAnalysis["WT.co_f"]=null},null,!0);return this}catch(d){this.errors.push(d),this.errorlogger(d)}},addQueryParameters:function(b,c){var d=this.DCS;if(0<b.length()&&!this.skip_qp){b.forEach(function(u,w){var v=u;if(!((this.skip_qp_no_value||this.skip_qp_no_equals)&&"undefined"===typeof u||this.skip_qp_no_equals&&""===u)){if("undefined"===typeof u||
null===u)v="undefined";d[w]=v}},this);var f=this.paidsearchparams.length?this.paidsearchparams.toLowerCase().split(","):[];for(var q=0;q<f.length;q++)if(ORA.common.QueryParamCache.contains(f[q],!0)){c.srch="1";break}}},dcsVar:function(){var b=this.trackingData;this.i18n&&(b.le="string"===typeof a.defaultCharset?a.defaultCharset:"string"===typeof a.characterSet?a.characterSet:"unknown");b.tv=ORA.analytics.versionStr;var c=ORA.common.QueryParamCache.getCache();this.addQueryParameters(c,b);!0===this.metatagAuto&&
ORA.common.visitMetaTags(this.dcsMetaTagsAutoScrape,a,this.DCSext);this.metanames&&ORA.common.visitMetaTags(this.dcsMetaTagArrScrape(this.metanames),a,this.DCSext)},dcsMetaTagArrScrape:function(b){return function(c,d,f){c=c.toLowerCase();-1!==b.indexOf(c)&&(f["meta_"+c]=d)}},dcsMetaTagsAutoScrape:function(b,c,d){0===b.indexOf("ORA.")?d[b]=c:0===b.indexOf("DCS.")?(b=b.split("DCS."),b[1]&&(d[b[1]]=c)):0===b.indexOf("DCSext.")&&(b=b.split("DCSext."),b[1]&&(d[b[1]]=c))},getPageAnalysis:function(){var b=
ORA.analytics.dcsRef.dcsFPC(),c=ORA.common.extendArray;ORA.analytics.pageAnalysis?c(["vt_f"]).forEach(function(d){ORA.analytics.pageAnalysis["WT."+d]&&delete ORA.analytics.pageAnalysis["WT."+d]}):ORA.analytics.pageAnalysis=ORA.analytics.dcsRef.genPageAnalysis();return ORA.paramsMerge(ORA.analytics.pageAnalysis,b)},genPageAnalysis:function(){try{if(ORA.fireEvent(new ORA.Event(ORA.Event.ANA_BEFORE_PAGE_ANALYSIS,ORA.Event.STATUS_SUCCESS)),!ORA.analytics.isOptedOut()){var b=this.trackingData,c=this.DCS,
d=this.DCSext,f=this.i18n;f&&(b.dep="");var q={},u;for(u in c)c.hasOwnProperty(u)&&void 0!==c[u]&&"function"!==typeof c[u]&&(q[u]=c[u]);for(var w in b)b.hasOwnProperty(w)&&""!==b[w]&&void 0!==b[w]&&"function"!==typeof b[w]&&(q["WT."+w]=b[w]);for(var v in d)d.hasOwnProperty(v)&&""!==d[v]&&void 0!==d[v]&&"function"!==typeof d[v]&&(f&&(b.dep=0===b.dep.length?v:b.dep+";"+v),q[v]=d[v]);f&&0<b.dep.length&&(q["WT.dep"]=b.dep);ORA.Debug.superfine("pageAnalysis: "+this.prettify(q),"ANA");ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_PAGE_ANALYSIS,
ORA.Event.STATUS_SUCCESS));return q}}catch(r){ORA.Debug.error("error in pageAnalyze: "+r.toString())}},doRequest:function(){var b=this.destinations,c=this.getPageAnalysis;ORA.common.TrackingPipeline.registerMutation("analyticsAnnotate",function(d){if(d.params.mutation&&(!0===d.params.mutation.pageview||!0===d.params.mutation.conversion||!0===d.params.mutation.click||!0===d.params.mutation.collect&&!1!==d.params.sendSessionInfo||!0===d.params.mutation.view)){var f=c(),q;for(q in f)f.hasOwnProperty(q)&&
!d.getParam(q)&&d.setParam(q,f[q]);d.setParam("ora.tag_id",ORA.getTagId());d.setParam("ora.tag_config",ORA.getContextName());ORA.Debug.debug(d.params.desc?"annotating "+d.params.desc+" w/ analytics page analysis":"annotating w/ analytics page analysis","ANA");ORA.Debug.trace("annotating payload w/ "+ORA.analytics.prettify(f),"ANA");ORA.Debug.trace("Endpoints: "+ORA.analytics.prettify(b),"ANA");if("collect"!==d.params.desc)for(f=0;f<b.length;f++)d.endpoints.push({endpoint:b[f].endpoint,timeout:b[f].timeout,
conf:ORA.analytics.dcsRef,protocolType:ORA.common.CommManager.GIF});ORA.fireEvent(new ORA.Event(ORA.Event.ANA_PV_MUTATE,ORA.Event.STATUS_SUCCESS))}},1);ORA.Debug.debug("doRequest() - register mutation","ANA")},pageAnalyze:function(){ORA.Debug.trace("pageAnalyze()");this.dcsVar();this.adclickparam&&0<this.adclickparam.length&&this.dcsAdSearch();this.pageAnalyzehasRun=!0},getTime:function(){return(new Date).getTime()},dumpCounter:0,spinLock:function(b){for(var c=this.getTime();this.getTime()-c<b;)this.dumpCounter++},
enQueue:function(b,c){var d=b;ORA.Debug.debug("enQueue() - action: "+JSON.stringify(d)+" msg: "+JSON.stringify(c),"ANA");d||(d="collect");this.queue.push({action:d,message:c})},doAction:function(b){ORA.Debug.debug("doAction() - cmd: "+this.prettify(b),"ANA");var c="action_"+b.action;b=b.message;this.pageAnalyzehasRun||this.pageAnalyze();b.event&&!b.element&&(b.element=ORA.analytics.elemOfEvent(b.event,{A:1}));if(ORA.analytics.isFn(this[c]))this[c](b)},action_collect:function(b){ORA.Debug.debug("action_collect()",
"ANA");this.doRequest(b)},dcsIsOnsite:function(b,c){var d=b;if(0<d.length){d=d.toLowerCase();if(d===window.location.hostname.toLowerCase())return!0;if(ORA.analytics.isFn(c.test))return c.test(d);if(0<c.length)for(var f=c.length,q=0;q<f;q++)if(d===c[q])return!0}return!1},dcsNavigation:function(b,c){var d="",f="",q=c.length,u;for(u=0;u<q;u++){var w=c[u];if(w.length&&(f=ORA.analytics.elemOfEvent(b,w),d=f.getAttribute&&f.getAttribute("id")?f.getAttribute("id"):"",f=f.className||"",d.length||f.length))break}return d.length?
d:f},dcsAdSearch:function(){if(a.links){var b=this.adclickparam+"\x3d",c=b.length;b=new RegExp(b,"i");var d=a.links.length,f=a.URL+"",q=f.search(b);if(-1!==q){var u=f.indexOf("\x26",q);var w=-1!==u?f.substring(q,u):f.substring(q,f.length);var v=new RegExp(w+"(\x26|#)","i")}for(f=0;f<d;f++)if(a.links[f].href){var r=a.links[f].href+"";w&&0<w.length&&(r=r.replace(v,"$1"));u=r.search(b);-1!==u&&(q=u+c,u=r.indexOf("\x26",q),u=-1!==u?r.substring(q,u):r.substring(q,r.length),this.trackingData.ad=this.trackingData.ad?
this.trackingData.ad+";"+u:u)}}}};ORA.Debug.debug("dcs class loaded","ANA")})(window,window.document);
(function(k,a,b){ORA.analytics.find=function(c){ORA.analytics.selectorEngine||(ORA.analytics.selectorEngine=ORA.analytics.findSelector());return ORA.analytics.selectorEngine(c)};ORA.analytics.findSelector=function(){var c=/MSIE (\d+)/.exec(b.userAgent);c=c?c[1]:99;var d=a.body;if(a.querySelectorAll&&d&&8<c)return function(f){return d.querySelectorAll(f)};if(k.jQuery)return k.jQuery.find;if(k.Sizzle)return k.Sizzle;if(k.YAHOO&&YAHOO.util&&YAHOO.util.Selector)return YAHOO.util.Selector.query;if("qwery"in
k)return qwery;k.YUI&&YUI().use("node",function(f){return f.all});return a.querySelectorAll&&d?function(f){return d.querySelectorAll(f)}:function(){return[]}};ORA.Debug.debug("selectorEngine initialized","ANA")})(window,window.document,window.navigator);
(function(){var k={cache:[],pollId:null,playerBoundCount:0,config:{load:!1,loadMeta:!1,pause:!0,quartile:!0,beacon:!1,beaconType:"auto",seek:!0,mute:!0,beaconRate:30,pctInc:25,volume:!0,bins:15,fullscreen:!0,playerId:"div[id^\x3d'vjs_video']:not([id$\x3d'_api']):not([id*\x3d'_component'])",trackCallback:function(a){ORA.click({data:a.args})},nameCallback:null,preProcess:null,transformCallback:null,beaconCurve:{60:10,120:20,300:30,420:45,600:60,1800:150},postMessage:!1,pollRate:250,poll:!0,playerReadyTimeout:20,
maxBinds:10,mediaTags:!0},videoStates:function(){this.data={ORA:{clip_n:null,clip_id:null,clip_secs:null,clip_mins:null,clip_ct:null,clip_perc:null,clip_ev:null,clip_duration:null,clip_t:"Flash",clip_player:"Brightcove vjs",clip_vol:null,clip_res:null,clip_player_res:null,clip_duration_n:null,clip_tv:"1.0.3",clip_mode:"FixedDuration",clip_player_ver:null,player_id:null,player_playlist_id:null,clip_video_id:null,clip_accountId:null,dl:41},_state:0,_lastBeacon:0,_lastQuartile:0,_volSettle:-1,_seekSettle:-1,
_loaded:!1,_duration:null,_timer:null,_start:!1,_sentLoad:!1,_myBeaconRate:0,_isMuted:!1,player:null,_fullScreen:!1,_isValidMeta:!1,_waitMeta:!1}},playEvent:function(a,b,c){var d=this.config,f=!1;if("play"===a.data._state||!a.data._loaded||a.data._waitMeta||0<a.data._seekSettle)return!1;!a.data._isValidMeta&&b.isReady_&&this.bcCallback(a,"meta",c);"pause"===a.data._state||"stop"===a.data._state?d.pause&&(a.data.ORA.clip_ev="Resume",f=!0,a.data._state="play"):(a.data.ORA.clip_ev="Play",f=a.data._loaded=
!0,a.data._state="play",a.data._lastBeacon=0,a.data._lastQuartile=0,a.data.ORA.clip_perc="0",a.data.ORA.clip_secs=null,a.data.ORA.clip_mins=null,a.data.ORA.clip_res=b.height()+"x"+b.width(),a.data._seekSettle=55);a.data._start=!0;return f},metaEvent:function(a,b,c){var d=this.config,f=!1,q=b.mediainfo;if(void 0===q)return f;var u=b.options();b.currentType()&&(a.data.ORA.clip_ct=b.currentType());"string"===typeof b.techName_&&(a.data.ORA.clip_t=b.techName_.toUpperCase());a.data.ORA.clip_id=q.id;a.data.ORA.player_id=
u["data-player"];a.data.ORA.clip_player_ver=videojs.VERSION;a.data.ORA.player_playlist_id=u["data-playlist-id"];a.data.ORA.clip_video_id=q.id;a.data.ORA.clip_accountId=q.account_id;this.setMediaDuration(a,q);a.data._duration||(a.data.ORA.clip_mode="Stream",a.data.ORA.clip_duration=null,a.data._duration=null);a.data._myBeaconRate=d.beaconRate;this.setName(a,q,b);this.setBins(a);d.mediaTags&&void 0!==q.tags&&0<q.tags.length&&this.metaTags(a,q);a.data._fullScreen=b.isFullscreen();a.data._sentLoad?a.data._loaded=
!0:this.bcCallback(a,"load",c);a.data._isValidMeta=!0;a.data._waitMeta=!1;d.loadMeta&&(f=!0,a.data.ORA.clip_ev="Meta",a.data.ORA.dl=41);return f},setMediaDuration:function(a,b){b.duration?(a.data.ORA.clip_duration=Math.floor(100*b.duration)/100,a.data._duration=b.duration):(a.data.ORA.clip_duration=null,a.data._duration=null)},setName:function(a,b,c){var d=this.config;a.data.ORA.clip_n=void 0!==b.name?b.name:b.src?b.src.split("/")[b.src.split("/").length-1].split(".")[0]:"not provided in meta";"function"===
typeof d.nameCallback&&(a.data.ORA.clip_n=d.nameCallback(c))},setBins:function(a){var b=this.config;if(b.bins&&a.data._duration&&0<a.data._duration){var c=Math.floor((a.data._duration+b.bins)/b.bins);a.data.ORA.clip_durration_n=(c-1)*b.bins+"-"+c*b.bins}},metaTags:function(a,b){try{for(var c=[],d=0;d<b.tags.length;d++){var f=b.tags[d].split("\x3d")[0];1<b.tags[d].split("\x3d").length?a.data.ORA["clip_tag_"+f]=b.tags[d].split("\x3d")[1]:c.push(f)}0<c.length&&(a.data.ORA.clip_tags=c.join(";"))}catch(q){}},
pauseEvent:function(a,b,c,d){b=this.config;var f=!1;if(0<a.data._seekSettle)return f;if(97<a.data.ORA.clip_perc)this.bcCallback(a,"complete",c);else{if(!a.data._loaded||!a.data._start||"start"===a.data._state&&"begin"===a.data._state)return f;b.pause&&(f=!0);a.data._state=d;a.data.ORA.clip_ev="Pause"}return f},completeEvent:function(a,b,c,d){b=!1;a.data._state=d;this.bcCallback(a,"timeupdate",c);"Complete"!==a.data.ORA.clip_ev&&(b=!0);a.data.ORA.clip_ev="Complete";a.data._start=!1;a.data.ORA.clip_perc=
100;a.data._loaded=!1;a.data._isValidMeta=!1;return b},errorEvent:function(a,b){a.data.ORA.clip_ev="Error ";a.data.ORA.clip_ev+=b.error_.type;return!0},progressEvent:function(a,b,c){var d=this.config,f=b.currentTime(),q=!1;0<a.data._seekSettle&&--a.data._seekSettle;5<Math.abs(Math.floor(100*f)/100-a.data.ORA.clip_secs)&&"complete"!==a.data._state&&this.bcCallback(a,"seek",c);a.data.ORA.clip_secs=Math.floor(f);a.data.ORA.clip_mins=Math.floor(f/60*100)/100;if(d.quartile&&this.processQuartile(a)||this.processBeacon(a,
f))return!0;0<=a.data._volSettle&&--a.data._volSettle;q=this.checkEnded(a,b,c,q);this.setBins(a);this.isMuted(a,b,c);this.isPaused(a,b,c);this.setScreen(a,b,c);this.setVolume(a,b);return q},isPaused:function(a,b,c){a.data._start||b.paused()||this.bcCallback(a,"play",c)},isMuted:function(a,b,c){b.muted()!==a.data._isMuted&&this.bcCallback(a,"mute",c)},checkEnded:function(a,b,c,d,f){b=f;"ended"===a.data._state&&(a.data.ORA.clip_ev="complete",a.data.ORA.clip_secs="0",a.data.ORA.clip_mins="0",a.data.ORA.clip_perc=
null,b=!1,a.data._state="ended");return b},setVolume:function(a,b){void 0!==b.volume()&&(b.volume()===isNaN?a.data.ORA.clip_vol=100:a.data.ORA.clip_vol=Math.floor(1E3*b.volume())/10)},setScreen:function(a,b,c){a.data._fullScreen!==b.isFullscreen()&&0<b.readyState()&&(a.data._fullScreen=b.isFullscreen(),b.isFullscreen()?this.bcCallback(a,"fullscreen",c):this.bcCallback(a,"fullscreenexit",c))},processQuartile:function(a){var b=this.config;if(a.data.ORA.clip_perc>=a.data._lastQuartile+b.pctInc)return a.data.ORA.clip_perc=
Math.floor(a.data.ORA.clip_perc/b.pctInc)*b.pctInc,a.data._lastQuartile=a.data.ORA.clip_perc,a.data.ORA.clip_ev="Quartile",!0;"complete"===a.data._state&&100!==a.data._lastQuartile?(a.data.ORA.clip_perc=100,a.data._lastQuartile=a.data.ORA.clip_perc,a.data.ORA.clip_ev="Quartile",a=!0):a=!1;return a},beaconCurve:function(a){var b=this.config,c;for(c in b.beaconCurve)if(b.beaconCurve.hasOwnProperty(c)&&a<=c)return b.beaconCurve[c];return null},processBeacon:function(a,b){var c=this.config,d=!1,f=null!==
a.data.ORA.clip_mode&&"stream"===a.data.ORA.clip_mode.toLowerCase(),q=this.beaconCurve(b);try{("auto"===c.beaconType.toLowerCase()&&f||"curve"===c.beaconType)&&null!==beaconCurve?(0===b&&(a.data._lastBeacon=0),a.data._myBeaconRate=q):a.data._myBeaconRate=c.beaconRate}catch(u){a.data._myBeaconRate=c.beaconRate}b>a.data._lastBeacon+a.data._myBeaconRate&&c.beacon&&(a.data.ORA.clip_ev="Beacon",d=!0,a.data._lastBeacon+=a.data._myBeaconRate);return d},seekedEvent:function(a,b,c,d){c=this.config;b=b.currentTime();
var f=!1;a.data._lastBeacon=b;"ended"!==a.data._state&&c.seek&&0===a.data._seekSettle&&0!==b&&(a.data.ORA.clip_ev="Seek",f=!0,a.data._seekSettle=20);a.data._state=d;return f},cancelseekEvent:function(a){a.data._seekSettle=-1;return!1},fullscreenEvent:function(a,b){var c=!1;this.config.fullscreen&&b.isFullscreen()&&(a.data.ORA.clip_ev="Fullscreen",c=!0);return c},loadstartEvent:function(a){var b=!1;this.config.load&&(b=a.data._sentLoad=!1);return b},loadEvent:function(a){var b=!1;this.config.load&&
!a.data._sentLoad&&(a.data.ORA.clip_ev="Load",b=!0);a.data._sentLoad=!0;a.data._loaded=!0;return b},fullscreenexitEvent:function(a,b){var c=!1;this.config.fullscreen&&!b.isFullscreen()&&(a.data.ORA.clip_ev="Fullscreenexit",c=!0);return c},muteEvent:function(a,b){var c=!1;this.config.mute&&(b.muted()?(a.data.ORA.clip_ev="Muted",a.data._isMuted=!0):(a.data.ORA.clip_ev="UnMuted",a.data._isMuted=!1),a.data._isMuted=b.muted(),c=!0);return c},volumechangeEvent:function(a,b){var c=!1;!this.config.volume||
-1!==a.data._volSettle||a.data._isMuted||b.muted()||(a.data.ORA.clip_vol=Math.floor(1E3*b.volume())/10,a.data._volSettle=20,a.data.ORA.clip_ev="Volume",c=!0);return c},bcCallback:function(a,b,c){var d=document.getElementById(c),f=window.videojs(c).player(),q=!1,u=f.currentTime();window.ORA&&ORA.Debug&&"progress"!==b&&"timeupdate"!==b&&ORA.Debug.debug("video_bc Plugin event "+b,"ANA");a.data.ORA.clip_perc=u&&a.data._duration&&0<a.data._duration?Math.floor(u/a.data._duration*1E4)/100:null;a.data.ORA.dl=
40;this.loadedmetadataEvent=this.metaEvent;this.endEvent=this.completeEvent;this.timeupdateEvent=this.progressEvent;this.seekEvent=this.seekedEvent;"undefined"!==typeof this[b+"Event"]&&(q=this[b+"Event"](a,f,c,b,q));q&&this.sendTrackEvent(a,d)},sendTrackEvent:function(a,b){var c=this.config;window.ORA&&ORA.Debug.info("video_bc queueing data for "+a.data.ORA.clip_n+" : "+a.data.ORA.clip_ev,"ANA");var d={},f;for(f in a.data.ORA)a.data.ORA.hasOwnProperty(f)&&this.setTagParm(a,f,d);this.cache.push({element:this,
args:d,transform:c.transformCallback,data:a.data.ORA,videoEle:b});if("function"===typeof c.trackCallback)try{c.trackCallback(this.cache.pop())}catch(q){window.ORA&&ORA.Debug.info("video_bc Error with trackCallback","ANA")}},setTagParm:function(a,b,c){"number"===typeof a.data.ORA[b]?("clip_secs"===b||"clip_perc"===b||"clip_mins"===b)&&0===a.data.ORA[b]||isNaN(a.data.ORA[b])?delete c["WT."+b]:c["WT."+b]=a.data.ORA[b].toString():null===a.data.ORA[b]?delete c["WT."+b]:c["WT."+b]=a.data.ORA[b]},bindPlayer:function(a){var b=
"pause play end mute complete loadstart loadeddata resize progress seeked error meta timeupdate cancelseek volumechange loadedmetadata".split(" ");if(k.playerBoundCount>this.config.maxBinds)window.ORA&&ORA.Debug.info("video_bc max binds reached","ANA");else try{window.videojs(a).ready(function(){var c=new k.videoStates,d=this,f=k.config;c.data.player=this;b.forEach(function(q){(function(){this.config=f;d.on(q,function(){k.bcCallback(c,q,a)})}).apply(this,[q,a,c,d,f])});window.videojs(a).isReady_&&
k.bcCallback(c,"meta",a);window.ORA&&ORA.Debug.info("video_bc Plugin bound to player "+a,"ANA")})}catch(c){window.ORA&&ORA.Debug.info("video_bc Plugin error binding to player "+a,"ANA")}k.playerBoundCount++},waitForPlayer:function(a){var b=this,c=a;setTimeout(function(){void 0!==window.videojs&&0<document.querySelectorAll(k.config.playerId+':not([data-wt\x3d"wtBound"])').length?b.lookForPlayers():"infinite"===c||0<c?(isNaN(c)||c--,b.waitForPlayer(c)):window.ORA&&ORA.Debug.info("video_bc Plugin time out waiting for player",
"ANA")},500)},pollPlayer:function(a){var b=this;this.pollId=setInterval(function(){b.lookForPlayers()},a)},reset:function(){if(this.pollId){clearInterval(this.pollId);var a=document.querySelectorAll(k.config.playerId);if(0<a.length)for(var b=0;b<a.length;b++)a[b].setAttribute("data-wtbc","")}},lookForPlayers:function(){try{var a=document.querySelectorAll(this.config.playerId)}catch(c){window.ORA&&ORA.Debug.info("video_bc Plugin error with selector "+this.config.playerId,"ANA")}if(void 0!==window.videojs&&
0<document.querySelectorAll(this.config.playerId+":not([data-wtbc\x3d'Bound'])").length)for(var b=0;b<a.length;b++)this.bindPlayer(a[b].id),a[b].setAttribute("data-wtbc","Bound"),window.ORA&&ORA.Debug.info("video_bc Plugin binding to player "+a[b].id,"ANA")},bcInit:function(a){a=a.config||{};this.bcInfo("video_bc Plugin init start");if(void 0===a.enable||a.enable){var b=ORA.common._getIEVer();if(b&&11>=b)this.bcInfo("video_bc Plugin requires \x3e ie11, disabling plugin");else{for(var c in this.config)this.config.hasOwnProperty(c)&&
void 0!==a[c]&&(this.config[c]=a[c]);this.reset();this.config.poll?this.pollPlayer(this.config.pollRate):(this.lookForPlayers(),this.waitForPlayer(this.config.playerReadyTimeout));this.bcInfo("video_bc Plugin init complete")}}else this.bcInfo("video_bc Plugin is disabled")},bcInfo:function(a){window.ORA&&ORA.Debug.info(a,"ANA")},init:function(a){k.bcInit(a)}};window.ORA&&ORA.regPlugin&&(ORA.regPlugin("bc",k.init),window.ORA.Debug.info("video_html5 Plugin registration request","ANA"),ORA.analytics.plugins||
(ORA.analytics.plugins={}),ORA.analytics.plugins.bcVideo=k)})();
(function(){var k={fragCfg:{paramHandling:"none",prefix:"fragment",addAnchorName:"none",virtualDl:26,testFragment:null,testPayload:null},fragData:{fragName:null,parmObj:{},fragFullStr:null},setConfig:function(a){var b=k.fragCfg,c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c])},init:function(a,b){var c=k,d=c.fragData,f=c.fragCfg,q=b||function(){};c.setConfig(a.config||{});void 0!==f.enable&&!1===f.enable&&(ORA.Debug.debug("Plugin is disabled","ANA-fragment"),q());d.fragFullStr=f.testFragment||window.location.hash;
d.fragFullStr?(c.updateFragData(d.fragFullStr),ORA.analytics.addMutation("fragmentIdentifier",c.addFragMutation),f.virtualPageView&&(ORA.Debug.debug("Sending virtual fragment page view","ANA-fragment"),ORA.click({data:{"wt.dl":f.virtualDl,"wt.anchor_name":d.fragName}}))):ORA.Debug.debug("No fragments found for the URL on this page","ANA-fragment");q();ORA.Debug.debug("fragment Plugin init complete","ANA-fragment")},updateFragData:function(a){var b=k.fragData,c=[];a&&(c=a.split("?"));ORA.Debug.debug("Updating Fragment data using: "+
a,"ANA-fragment");b.fragFullStr=a;b.fragName=c[0];b.parmObj=1<c.length?ORA.common.getQryParams(c[1]):{}},addFragMutation:function(a){k.isClickEvent(a.payload["wt.dl"])&&(a=k.applyClickEvent(a));return a},isClickEvent:function(a){var b=this.fragCfg,c=this.isClickEvent;c.applyClickEventOnly||(c.applyClickEventOnly=void 0===b.applyClickEventOnly||!1===b.applyClickEventOnly);return void 0!==a&&"21"===a&&void 0!==b.applyClickEventOnly&&!0===b.applyClickEventOnly?!0:c.applyClickEventOnly},applyClickEvent:function(a){var b=
this.fragData,c=this.fragCfg,d="";"addPrefix"===c.paramHandling&&(d=c.prefix+"_");for(var f in b.parmObj)b.parmObj.hasOwnProperty(f)&&(a.payload[d+f]=b.parmObj[f]);switch(c.addAnchorName){case "name":a.payload["wt.anchor_name"]=b.fragName;break;case "fullString":a.payload["wt.anchor_name"]=b.fragFullStr}return a},rmFragMutation:function(){ORA.analytics.rmMutation("fragmentIdentifier")}};ORA.Debug.debug("fragmentIdentifier - Registering Plugin","ANA-fragment");ORA.regPlugin("fragment",k.init,{blockCollect:!0});
ORA.analytics.plugins||(ORA.analytics.plugins={});ORA.analytics.plugins.fragment||(ORA.analytics.plugins.fragment={});ORA.analytics.plugins.fragment.updateFragData=k.updateFragData;window.QUnit&&(ORA.analytics.plugins.fragment=k)})();
(function(){var k=this,a="onmousedown",b="scroll",c=50,d=null,f="default",q=(new Date).getTime(),u=5,w=null,v=!1,r=function(g,t,y){return parseInt(g,10)>=parseInt(t,10)?y-1:Math.floor(y/parseInt(t,10)*parseInt(g,10))},e=function(g){g=Math.round(Number(g));1>g&&(g=1);100<g&&(g=100);for(var t={},y=g;100>=y;)t[y]=!1,y+=g;return t};w=e(u);var m=function(){var g=0,t=0;"number"===typeof window.pageYOffset?(t=window.pageYOffset,g=window.pageXOffset):document.body&&document.body.scrollLeft&&document.body.scrollTop?
(t=document.body.scrollTop,g=document.body.scrollLeft):document.documentElement&&document.documentElement.scrollLeft&&document.documentElement.scrollTop&&(t=document.documentElement.scrollTop,g=document.documentElement.scrollLeft);return{x_offset:g,y_offset:t}},x=function(g){var t=0,y=0;"number"===typeof window.innerWidth?(t=window.innerWidth,y=window.innerHeight):document.documentElement&&document.documentElement.clientWidth&&document.documentElement.clientHeight?(t=document.documentElement.clientWidth,
y=document.documentElement.clientHeight):document.body&&document.body.clientWidth&&document.body.clientHeight&&(t=document.body.clientWidth,y=document.body.clientHeight);var A=m();return g.clientX>t||0>g.clientX||g.clientY>y||0>g.clientY||"NaN"===g.clientX||"NaN"===A.x_offset||"NaN"===t||"Nan"===y?{}:{x:g.clientX+A.x_offset,y:g.clientY+A.y_offset}},l={},p=function(g){var t=g.target||g.srcElement,y=d(t);if(document.querySelector){y=document.querySelector(y).getBoundingClientRect();var A=y.width;t=
y.height;var B=m(),C=B.x_offset;B=B.y_offset;B=B+g.clientY-(B+y.top);g=r(C+g.clientX-(C+y.left),A,c);t=r(B,t,c);return{x:g,y:t}}return{x:t.clientX,y:t.clientY}},h=function(g){var t=(new Date).getTime();g["wt.hm_timeSpan"]=t-q},n=function(g){try{if(window&&window.MMExperience&&"object"===typeof window.MMExperience&&v){for(var t=Object.getOwnPropertyNames(window.MMExperience).sort(),y="",A=0;A<t.length;A++){var B=t[A],C="";if(window.MMExperience.hasOwnProperty(B)){for(var D=window.MMExperience[B],E=
Object.getOwnPropertyNames(D).sort(),F=D,H="",G=0;G<E.length;G++){var I=E[G],K=F[I],J="";G+1<E.length&&(J="|");H+=""+I.toLowerCase()+":"+K.toLowerCase()+J}C=H}F="";A+1<t.length&&(F=",");y+=""+B.toLowerCase()+"\x3d"+C+F}g["wt.hm_experience"]=y}}catch(L){}};this.genClickData=function(g){var t=g||window.event;t&&(t.target||t.srcElement)||ORA.Debug.debug("WARNING: defaultClickHandler unable to detect target element, not sending heatmap track","ANA-hm");var y=t.target||t.srcElement;ORA.hasVal(y.offsetLeft)&&
ORA.hasVal(t.clientX)||ORA.Debug.debug("WARNING: defaultClickHandler event is missing click coords or target dom object missing offset, not sending heatmap track","ANA-hm");var A=x(t),B=d(y),C=m();A&&B&&C||ORA.Debug.debug("WARNING: defaultClickHandler missing scroll or targetId, not sending heatmap track","ANA-hm");g=p(g);var D=function(){var E=t.target||t.srcElement;return{h:E.clientHeight||0,w:E.clientWidth||0}};y={"wt.hm_winx":t.clientX,"wt.hm_winy":t.clientY,"wt.hm_targetx":y.offsetLeft,"wt.hm_targety":y.offsetTop,
"wt.hm_scrolldx":C.x_offset,"wt.hm_scrolldy":C.y_offset,"wt.hm_x":A.x-y.offsetLeft,"wt.hm_y":A.y-y.offsetTop,"wt.hm_width":y.clientWidth,"wt.hm_height":y.clientHeight,"wt.hm_scaled_x":g.x,"wt.hm_scaled_y":g.y,"wt.hm_target_id":B,"wt.hm_targetw":D().w,"wt.hm_targeth":D().h,"wt.hm_resolution":c,"wt.hm_selectorType":f,"wt.dl":125};h(y);n(y);return y};this.getHorzScroll=function(g,t){return"CSS1Compat"===document.compatMode?g.clientHeight||window.innerHeight||0:t.clientHeight||0};this.genScrollData=function(g){var t=
document.documentElement,y=document.body,A=getHorzScroll(t,y);t=Number((A+(window.pageYOffset||t&&t.scrollTop||y.scrollTop))/Math.max(y.scrollHeight,t.scrollHeight,y.offsetHeight,t.offsetHeight,y.clientHeight,t.clientHeight)*100).toFixed(0);switch(g){case "regular":if("boolean"!==typeof w[t]||w[t])return null;w[t]=!0;break;case "start":break;default:return null}g={"wt.hm_scrollDepth":t,"wt.hm_scrollDepthType":g,"wt.dl":125};h(g);n(g);return g};k.setEventClickName=function(g){a=g};k.setEventScrollName=
function(g){b=g};k.getEventClickName=function(){return a};k.getEventScrollName=function(){return b};k.removeClickHandler=function(g){ORA.removeDOMEvent(document,ORA.getSafeEventName(document,a),g)};k.removeScrollHandler=function(g){ORA.removeDOMEvent(document,ORA.getSafeEventName(document,b),g)};k.addClickHandler=function(g){ORA.addDOMEvent(document,ORA.getSafeEventName(document,a),g)};k.addScrollHandler=function(g){ORA.addDOMEvent(document,ORA.getSafeEventName(document,b),g)};k.replaceDefaultClickHandler=
function(g){k.removeClickHandler(k.defaultClickHandler);k.addClickHandler(g)};k.replaceDefaultScrollHandler=function(g){k.removeScrollHandler(k.defaultScrollHandler);k.addScrollHandler(g)};k.defaultClickHandler=function(g){try{var t=k.genClickData(g);ORA.Debug.trace(ORA.common.JSONPrettify(t));ORA.click({data:t})}catch(y){ORA.Debug.error("WARNING: click heatmap failed to track","013",y,"clickHeatmap defaultHandler")}};k.defaultScrollHandler=function(){try{if(!defaultScrollHandler.caller&&v){var g=
k.genScrollData("regular");g&&(ORA.Debug.trace(ORA.common.JSONPrettify(g)),ORA.click({data:g}))}}catch(t){ORA.Debug.error("WARNING: scroll heatmap failed to track","13",t,"scrollHeatmap defaultHandler")}};var z=function(){var g=k.genScrollData("start");g&&(ORA.Debug.trace(ORA.common.JSONPrettify(g)),ORA.click({data:g}))};k.reset=function(){k.removeClickHandler(k.defaultClickHandler);k.removeScrollHandler(k.defaultScrollHandler)};k.setup=function(g){g=g||{};l={"default":ORA.common.getObjId,strict:ORA.common.getObjIdStrict,
classes:ORA.common.getObjIdClasses};g.selectorEngineType&&(f=g.selectorEngineType);d=l.hasOwnProperty(f)?l[f]:l["default"];g.clickEventName&&(a=g.clickEventName);g.resolution&&(c=g.resolution);g.scrollStep&&(u=g.scrollStep,w=e(u));g.maxymiserEnable&&(v=g.maxymiserEnable);k.addClickHandler(k.defaultClickHandler);k.addScrollHandler(k.defaultScrollHandler)};ORA.Debug.debug("heatmap - Registering Plugin","ANA-hm");ORA.regPlugin("heatmap",function(g,t){ORA.Debug.debug("heatmap - init start","ANA-hm");
var y=t||function(){};if(g&&g.config&&void 0!==g.config.enable&&!g.config.enable)ORA.Debug.info("heatmap Plugin is disabled","ANA"),y();else{var A=ORA.analytics.getIEVer();A&&9>A?(ORA.Debug.info("heatmap Plugin requires \x3e IE9, disabling plugin","ANA"),y()):(k.setup(g.config),ORA.Debug.debug("heatmap - Starting scroll tracking","ANA-hm"),document&&document.body&&("complete"===document.readyState||"interactive"===document.readyState)?z():document.addEventListener("DOMContentLoaded",function(){z()}),
y(),ORA.Debug.debug("heatmap - init complete ","ANA-hm"))}});ORA.analytics.plugins||(ORA.analytics.plugins={});ORA.analytics.plugins.heatmap||(ORA.analytics.plugins.heatmap={});ORA.analytics.plugins.heatmap=k})();
(function(){var k={cfg:{standardEvents:{download:!1,offsite:!1,onsite:!1,rightclick:!1,anchor:!1,javascript:!1,scrollTracking:!1},scroll_frequency:25,eventList:{},downloadtypes:"xls,doc,pdf,txt,csv,zip,docx,xlsx,rar,gzip",socialTypes:{},trackSocial:!0},init:function(a,b){var c=a.config||{},d=b||function(){};ORA.Debug.debug("Event Track plugin Start Init","ANA-ET");try{for(var f in c)c.hasOwnProperty(f)&&(k.cfg[f]=c[f]);if(void 0!==k.cfg.enable&&!k.cfg.enable)return ORA.Debug.debug("Event Track plugin is disabled - exiting",
"ANA-ET"),d();var q=ORA.getIEVer();if(q&&9>q)return ORA.Debug.info("requires \x3e\x3d ie9, disabling plugin","ANA-ET"),d();ORA.Debug.info("Adding standard events","ANA-ET");k._addStandardEvents();if(!document.querySelectorAll)return ORA.Debug.info("Event Track plugin requires querySelectorAll function","ANA-ET"),d(),!1;k._addMatches();ORA.Debug.info("Binding to objects","ANA-ET");k._bind()}catch(u){ORA.Debug.error("Event Track plugin Init Error"+u.message,"ANA-ET"),d()}d();ORA.Debug.debug("Event Track plugin Start Init Complete",
"ANA-ET")},_getFullUrl:function(a){if("A"===a.nodeName){var b=a.cloneNode(!0);b.href=a.href;return b}return a},_eventCallback:function(a,b){try{for(var c=a.eventTrigger&&a.eventTrigger.split(" ")||["mousedown"],d=function(q,u,w){w._evtMsg(q);try{var v=w._fnCreator(a.eventCallback)(q,u);w._isEmptyObj(v)||(ORA.collect({config:{endpoints:[{endpoint:ORA.analytics.getEndPoint(),protocolType:"beaconProtocol"}],applyMutations:!0},data:v.data}),w._fnCreator(a.fnFinishCallback)(q))}catch(r){ORA.Debug.error("Event Track error in event callback: "+
r.message,"ANA-ET")}},f=0;f<c.length;f++)"immediate"!==c[f].toLowerCase()?(ORA.Debug.info("Event Track for "+b+" bind to "+a.selector+" event: "+c[f],"ANA"),this._delegate(document,c[f].toLowerCase(),a.selector,d,a,this)):(ORA.Debug.info("Event Track Immediate: "+b,"ANA"),d(null,null,this))}catch(q){ORA.Debug.error("Error binding adding selector for: "+b+" err: "+q.message,"ANA-ET")}},_delegate:function(a,b,c,d,f,q){function u(v){return function(r,e,m){var x=r.target||r.srcElement,l=x;"scroll"===
r.type&&d.call(null,r,e,m);for("A"===x.nodeName&&x.href&&(l=k._getFullUrl(x));l&&l!==document;)l.matches(c)&&d.call(l,r,e,m),l=l.parentNode}.apply(this,[v,f,q])}if(a.addEventListener)a.addEventListener(b,function(v){u(v)});else{var w=b;"click"===b&&(w="mousedown");a.attachEvent("on"+w,function(v){u(v)})}},_bind:function(){var a=this.cfg.eventList,b;for(b in a)a.hasOwnProperty(b)&&this._eventCallback(a[b],b)},_evtMsg:function(a){if(a){var b="Event Triggered:"+a.type+" node:"+(a.srcElement||a.target).nodeName+
" #";b+=(a.srcElement||a.target).id+" class:"+(a.srcElement||a.target).className;ORA.Debug.info(b,"ANA-ET")}else ORA.Debug.info("Event Triggered for immediate event","ANA-ET")},_fnCreator:function(a){return"string"===typeof a?new Function("e",a):"function"===typeof a?a:function(){}},_addMatches:function(){Element.prototype.matches||(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.msMatchesSelector||
Element.prototype.oMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.webkitMatchesSelector||function(a){a=(this.document||this.ownerDocument).querySelectorAll(a);var b=a.length;for(--b;0<=b&&a.item(b)!==this;)--b;return-1<b})},_isRightClick:function(a){a=a||window.event;if(a.which)a=3===a.which;else if(a.button)a=2===a.button;else return!1;return a},_getHrefInfo:function(a){a=a.target||a.srcElement||{};var b={},c=a,d=document.createElement("a");a=this._findA(a);
if(!a.href)return{};d.href=a.href;b.dcssip=d.hostname?d.hostname.split(":")[0]:window.location.hostname;d.pathname&&0!==d.pathname.indexOf("/")?b.dcsuri="/"+d.pathname:b.dcsuri=d.pathname?d.pathname:"/";d.search&&(b.dcsqry=d.search.substring(d.search.indexOf("?")+1,d.search.length));b.dcsref=document.referrer;b["WT.nv"]=ORA.common.getObjId(c);b["WT.dl"]="24";return this._cleanPayload(b)},_cleanPayload:function(a){for(var b in a)a.hasOwnProperty(b)&&!a[b]&&delete a[b];return a},_findA:function(a){for(;a&&
"A"!==a.nodeName;)a=a.parentNode;return a},_checkOnsiteDom:function(a,b){var c=ORA.analytics.dcsRef._onsitedoms;c.test||(1===c.length&&""===c[0]&&(c=[location.host.split(":")[0]]),c=new RegExp(c.join(",").toLowerCase().replace(",","|").replace(/^\s*/,"").replace(/\s*$/,"")));return!(k._isRightClick(b)||!c.test(a.hostname))},_isEmptyObj:function(a){if("object"!==typeof a)return!0;for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},_addStandardEvents:function(){var a={download:"_addDownloadTracking",
offsite:"_addOffsiteTracking",onsite:"_addOnsiteLinkTracking",anchor:"_addAnchorTracking",rightclick:"_addRightClickTracking",javascript:"_addJavaScriptTracking",scrollTracking:"_addScrollTracking"},b;for(b in this.cfg.standardEvents)if(this.cfg.standardEvents.hasOwnProperty(b)&&this.cfg.standardEvents[b])this[a[b]]()},_addDownloadTracking:function(){ORA.Debug.info("Event Track plugin Add download tracking","ANA-ET");for(var a=[],b=k.cfg.downloadtypes.toLowerCase().split(","),c=0;c<b.length;c++)a.push('A[href*\x3d".'+
b[c]+'" i]');k.cfg.eventList.download={eventTrigger:"click",selector:a.join(","),eventCallback:function(d){var f=d.target||d.srcElement||d.target||{},q=k._getHrefInfo(d);ORA.Debug.debug("Download Callback Called");if(k._isRightClick(d)||!q)return{};q["WT.ti"]="Download:"+f.textContent||f.innerText;q["WT.dl"]="20";return{data:q}}}},testSocial:function(a,b,c){for(var d=0;d<a[b].length;d++)if(-1<c.toLowerCase().indexOf(a[b][d].toLowerCase()))return!0;return!1},isSocial:function(a){var b=k.cfg.socialTypes,
c;for(c in b)if(b.hasOwnProperty(c)&&k.testSocial(b,c,a))return c;return null},_addOnsiteLinkTracking:function(){ORA.Debug.info("Event Track plugin add onsite link tracking","ANA-ET");for(var a=k.cfg.downloadtypes.toLowerCase().split(","),b=':not([href*\x3d"javascript:"])',c=0;c<a.length;c++)b+=':not([href*\x3d".'+a[c]+'" i])';a=['A:not([href^\x3d"//"])'+b];c=[location.hostname];ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&(c=ORA.analytics.dcsRef._onsitedoms);if(!c.test){if(""===c||0===
c[0].length)c=[location.hostname];for(var d=0;d<c.length;d++)a.push('A[href*\x3d"'+c[d]+'"]'+b)}k.cfg.eventList.onsite={eventTrigger:"click",selector:a.join(","),eventCallback:function(f){var q=f.target||f.srcElement||{},u=k._getHrefInfo(f);ORA.Debug.debug("Onsite Link Callback Called");if(k._isEmptyObj(u))return{};for(;q&&"A"!==q.nodeName;)q=q.parentNode;if(!k._checkOnsiteDom(q,f))return ORA.Debug.debug("Onsite Link Callback Called - fails onsite test. Exiting"),{};u["WT.ti"]="Onsite:"+u.dcssip+
u.dcsuri;u.dcsqry&&(u["WT.ti"]+=u.dcsqry);u["WT.dl"]="1";return{data:u}}}},_addOffsiteTracking:function(){ORA.Debug.info("Event Track plugin add offsite tracking","ANA-ET");var a=['A:not(A[href*\x3d"javascript:"])'],b=[location.hostname];ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&(b=ORA.analytics.dcsRef._onsitedoms);if(!b.test){a=[];""===b&&(b=[location.host]);for(var c=0;c<b.length;c++)a.push('A:not([href*\x3d"'+b[c]+'"]):not([href*\x3d"javascript:"])')}k.cfg.eventList.offsite={eventTrigger:"click",
selector:a.join(","),eventCallback:function(d){var f=d.target||d.srcElement||{},q=k._getHrefInfo(d);ORA.Debug.debug("Offsite Callback Called");if(k._isEmptyObj(q))return{};for(;f&&"A"!==f.nodeName;)f=f.parentNode;var u=k.isSocial(f.href);u&&k.cfg.trackSocial&&(q["WT.soc_action"]=u+":click");if(k._checkOnsiteDom(f,d))return ORA.Debug.debug("Offsite Callback Called - fails offsite test exiting"),{};q["WT.ti"]="Offsite:"+q.dcssip+q.dcsuri;q.dcsqry&&(q["WT.ti"]+=q.dcsqry);q["WT.dl"]="24";return{data:q}}}},
_addRightClickTracking:function(){ORA.Debug.info("Event Track plugin add right click tracking","ANA-ET");for(var a=[],b=k.cfg.downloadtypes.toLowerCase().split(","),c=0;c<b.length;c++)a.push('A[href*\x3d".'+b[c]+'" i]');k.cfg.eventList.rightClick={eventTrigger:"mousedown",selector:a.join(","),eventCallback:function(d){ORA.Debug.debug("Rightclick Callback Called");if(!k._isRightClick(d)&&!k.cfg.testRightClick)return ORA.Debug.debug("RightClick Callback Called - exiting fails rightclick test"),{};var f=
d.element||d.srcElement||d.target||{};d=k._getHrefInfo(d);if(!d)return{};d["WT.ti"]="RightClick:"+f.textContent||f.innerText;d["WT.dl"]="25";return{data:d}}}},_addJavaScriptTracking:function(){ORA.Debug.info("Event Track plugin add javascript tracking","ANA-ET");k.cfg.eventList.javaScript={eventTrigger:"click",selector:'A[href*\x3d"javascript:"]',eventCallback:function(a){var b=a.element||a.srcElement||a.target||{};a=k._getHrefInfo(a);if(k._isEmptyObj(a))return{};ORA.Debug.debug("JavaScript Callback Called");
a["WT.ti"]=b.innerHTML?"JavaScript:"+b.innerHTML:"JavaScript:";a["WT.dl"]="22";a.dcssip=window.location.hostname;a.dcsuri=b.href;return{data:a}}}},_addAnchorTracking:function(){ORA.Debug.info("Event Track plugin add anchor tracking","ANA-ET");var a=window.location.pathname.split("/").pop();k.cfg.eventList.anchorTracking={eventTrigger:"click",selector:'A[href^\x3d"#"],A[href*\x3d"'+a+'#"]',eventCallback:function(b,c){var d=b.target||b.srcElement||{},f=k._getHrefInfo(b);if(k._isEmptyObj(f))return{};
for(ORA.Debug.debug("Anchor Callback Called");d&&"A"!==d.nodeName;)d=d.parentNode;if(!k._checkOnsiteDom(d,b)||!c.hasHash(d))return ORA.Debug.debug("Anchor Callback Called - no Hash address found, or offsite link - exiting hash:"+d.hash,"ANA-ET"),{};f["WT.ti"]="Anchor:"+(d.hash||"#");f["WT.dl"]="21";c.checkFragment(d);return{data:f}},hasHash:function(b){return b.hash&&-1<b.hash.indexOf("#")},checkFragment:function(b){ORA.analytics.plugins&&ORA.analytics.plugins.fragment&&ORA.analytics.plugins.fragment.updateFragData&&
ORA.analytics.plugins.fragment.updateFragData(b.hash)}}},_isMissingSent:!1,_getScrollPayload:function(a,b){return{"WT.page_scroll_depth":100<a*b?100:a*b,"WT.dl":"71"}},_addScrollTracking:function(){ORA.Debug.info("Event Track plugin add anchor tracking","ANA-ET");k.cfg.eventList.scrollTracking={selector:"",eventTrigger:"scroll",eventCallback:function(){var a=k.cfg.scroll_frequency,b=ORA.common.scrollEventCallback(a);window.evtScrollTracker||(window.evtScrollTracker={});if(!window.evtScrollTracker[b]){window.evtScrollTracker[b]=
!0;if(!k._isMissingSent){k._isMissingSent=!0;for(var c=1;c<b;c++)window.evtScrollTracker.hasOwnProperty(c)||(window.evtScrollTracker[c]=!0,ORA.collect({config:{endpoints:[{endpoint:ORA.analytics.getEndPoint(),protocolType:"beaconProtocol"}],applyMutations:!0},data:k._getScrollPayload(c,a)}))}return{data:k._getScrollPayload(b,a)}}return{}}}},addTracking:function(a,b){"object"===typeof a&&"string"===typeof b?k._eventCallback(a,b):ORA.Debug.debug("Ignoring addTrack call - obj or trigger type error",
"ANA-ET")}};ORA.regPlugin("evtTrack",k.init);ORA.analytics.plugins.evtTrack||(ORA.analytics.plugins.evtTrack={});ORA.analytics.plugins.evtTrack.addTracking=k.addTracking;ORA.analytics.plugins.evtTrack.eventTrack=k})();
(function(){function k(){if(this.href){var h=this.href;if(l.hasOwnProperty("addHash")||l.hasOwnProperty("addParam")||l.hasOwnProperty("autoSelect")){var n=h;if(l.autoSelect||l.addHash)n=a(n);if(l.autoSelect&&n===h||!l.autoSelect&&l.addParam)n=b(n);h=n}else if("parameter"!==l.addIdTreatment&&(h=a(this.href)),"auto"===l.addIdTreatment&&h===this.href||"parameter"===l.addIdTreatment)h=b(this.href);this.href=h}}function a(h){var n=m()||{};if(h&&-1<h.indexOf("#")||!n.id||!l.guard)return h;l.encode&&window.btoa&&
(n.id=btoa(n.id));ORA.Debug.debug("Adding hash to href: "+h+"#xd_co_f\x3d"+n.id+l.guard,"crossDomain-ANA");return h+"#xd_co_f\x3d"+n.id+l.guard}function b(h){var n=m();if(!h||n&&!n.id||!l.guard)return h;l.encode&&window.btoa&&(n.id=btoa(n.id));ORA.Debug.debug("Adding parameters to href: "+h+"?xd_co_f\x3d"+n.id+l.guard,"crossDomain-ANA");a:{n="xd_co_f\x3d"+n.id;var z=h.replace(RegExp("(\x26|\\?)xd_co_f\x3d[^\x26|#]*"),"$1"+n);if(h&&-1===h.indexOf("xd_co_f\x3d"))if(-1!==h.indexOf("?")){h=-1!==h.indexOf("#")?
-1!==h.split("#")[0].indexOf("?")?h.split("?")[0]+"?"+n+"\x26"+h.split("?")[1]:h.split("#")[0]+"?"+n+"#"+h.split("#")[1]:h.split("?")[0]+"?"+n+"\x26"+h.split("?")[1];break a}else z=-1!==h.indexOf("#")?h.split("#")[0]+"?"+n+"#"+h.split("#")[1]:h+"?"+n;h=z}return h}function c(h){var n=/[^A-Z0-9+\/=]/i,z=h.length;if(!z||0!==z%4||n.test(h))return!1;n=h.indexOf("\x3d");return-1===n||n===z-1||n===z-2&&"\x3d"===h[z-1]}function d(h,n){var z=h.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),g;(z=(new RegExp("[\\?\x26]"+
z+"\x3d([^\x26#]*)")).exec(n||location.search))&&(g=decodeURIComponent(z[1].replace(/\+/g," ")))&&c(g)&&window.atob&&(g=atob(g));return g}function f(h,n){var z,g=h.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");(g=(new RegExp("[#]"+g+"\x3d(.*)"+l.guard)).exec(n||location.hash))&&(z=decodeURIComponent(g[1].replace(/\+/g," ")))&&c(z)&&window.atob&&(z=atob(z));return z}function q(h,n,z,g){function t(A){return function(B){for(var C=B.target;C&&C!==document;){var D=C;if("A"===D.nodeName){var E=D.cloneNode(!0);
E.href=D.href;D=E}if(!D.matches)break;if(D.matches(n))break;if(D.matches(h)){g.call(C,B);break}C=C.parentNode}}.apply(this,[A])}if(document.addEventListener)document.addEventListener(z,t);else{var y=z;"click"===z&&(y="mousedown");document.attachEvent("on"+y,t)}}function u(h){if(x&&h.payload["wt.co_f"]!==x){ORA.Debug.debug("Resessionizing from "+h.payload["wt.co_f"]+"to"+x,"crossDomain-ANA");h.payload["wt.co_f"]=x;h=m();h.id=x;var n=ORA.analytics.dcsRef,z=n.FPCConfig.expireDate||new Date((new Date).getTime()+
63113851500),g="";n.FPCConfig.sessionOnly||(g="; expires\x3d"+z.toGMTString());ORA.analytics.setCookie(n.FPCConfig.name||"ORA_FPC",{id:h.id},""===n.FPCConfig.domain?g+"; path\x3d/":g+"; path\x3d/; domain\x3d"+n.FPCConfig.domain)}ORA.analytics.rmMutation("crossDomain")}function w(h){for(var n in h)h.hasOwnProperty(n)&&(l[n]=h[n]);return l}function v(h){var n=[location.hostname],z=['A[href*\x3d"'+location.hostname+'"]'];!l.ignoreOnsiteDoms&&ORA.analytics.dcsRef&&ORA.analytics.dcsRef._onsitedoms&&!n.test&&
""!==ORA.analytics.dcsRef._onsitedoms[0]&&(n=ORA.analytics.dcsRef._onsitedoms);if(n.test)ORA.Debug.debug("crossDomain does not support using regex for onsitedom list - using localhost","crossDomain-ANA");else{z=[];""===n&&(n=[location.host]);for(var g=0;g<n.length;g++)z.push('A[href*\x3d"'+n[g]+'/"]')}z.push('A[href*\x3d"javascript:"],A[href*\x3d"mailto:"],A[href*\x3d"tel:"],A[href*\x3d"sms:"]');n=z.join(",");"localhost"!==h&&(n=n.concat(",",h));ORA.Debug.debug("CrossDomain using deny list: "+n,"crossDomain-ANA");
return n}function r(){Element.prototype.matches||(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.webkitMatchesSelector,Element.prototype.matches=Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector||function(h){h=(this.document||this.ownerDocument).querySelectorAll(h);var n=h.length;for(--n;0<=n&&h.item(n)!==this;)--n;return-1<n})}
function e(){if(!l.enable)return ORA.Debug.info("crossDomain Plugin is disabled","crossDomain-ANA"),!0;if(l.hasOwnProperty("addHash")||l.hasOwnProperty("addParam")||l.hasOwnProperty("autoSelect")){if(!(l.autoSelect||l.addHash||l.addParam))return ORA.Debug.info("Plugin config invalid: Must specify at least one way of adding visitor`s ID","crossDomain-ANA"),!0}else if("auto"!==l.addIdTreatment&&"hash"!==l.addIdTreatment&&"parameter"!==l.addIdTreatment)return ORA.Debug.info("Plugin config invalid: Must specify at least one way of adding visitor`s ID",
"crossDomain-ANA"),!0;var h=ORA.getIEVer();return h&&9>h?(ORA.Debug.info("Browser is not compatible, requires IE9+","crossDomain-ANA"),!0):!1}function m(){var h=ORA.analytics.dcsRef,n="ORA_FPC";h&&h.FPCConfig&&h.FPCConfig.name&&(n=h.FPCConfig.name);var z={};h=RegExp(""+n+"[^;]+").exec(document.cookie)||"";h=decodeURIComponent(h.toString().replace(/^[^=]+./,""));try{h&&h.split(":").forEach(function(g){z[g.split("\x3d")[0]]=g.split("\x3d")[1]})}catch(g){return null}return z}var x,l={enable:!0,guard:"~",
addIdTreatment:"auto",encode:!0,denyListSelector:"localhost",allowListSelector:"A",testSessionId:!1,ignoreOnsiteDoms:!1},p=function(){var h=document.createElement("br");return function(n){try{h.querySelector(n)}catch(z){return!1}return!0}}();ORA.Debug.info("crossDomain plugin Register (blocking)","crossDomain-ANA");ORA.regPlugin("crossDomain",function(h,n){var z=n||function(){},g=h.config;r();try{w(g);if(e())return z();var t=l.hasOwnProperty("whiteListSelector")?l.whiteListSelector:l.allowListSelector;
var y=l.hasOwnProperty("blackListSelector")?v(l.blackListSelector):v(l.denyListSelector);if(!p(t))return ORA.Debug.info("allowList selector is invalid - exiting: "+t,"crossDomain-ANA"),z();if(!p(y))return ORA.Debug.info("denyList selector is invalid - exiting: "+y,"crossDomain-ANA"),z();ORA.Debug.debug("binding using allowList:"+t+" denyList: "+y,"crossDomain-ANA");q(t,y,"mousedown",k);q(t,y,"click",k);if((x=f("xd_co_f")||d("xd_co_f"))||l.testSessionId)ORA.Debug.debug("Adding Mutation","crossDomain-ANA"),
ORA.analytics.addMutation("crossDomain",u,3);ORA.Debug.debug("crossDomain Start Init Complete (unblock)","crossDomain-ANA");return z()}catch(A){return ORA.Debug.debug("crossDomain plugin Init Error (unblock)"+A.message,"crossDomain-ANA"),z()}},{blockCollect:!0});ORA.analytics.plugins.crossDomain={};ORA.analytics.plugins.crossDomain.testNode=function(h){return eval(h)};ORA.analytics.plugins.crossDomain.deleteProperty=function(h){delete l[h]};ORA.analytics.plugins.crossDomain.addProperty=function(h,
n){l[h]=n}})();
(function(){var k=[],a=[],b=function(){if(window.onYouTubeIframeAPIReady){var e=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=function(){e();c()}}else window.onYouTubeIframeAPIReady=function(){c()}},c=function(){for(var e=document.querySelectorAll("IFRAME"),m=0;m<e.length;m++)e[m].src&&(0<=e[m].src.toLowerCase().indexOf("//www.youtube.com/embed")||0<=e[m].src.toLowerCase().indexOf("//www.unittest.com/embed"))&&"ytBound"!==e[m].getAttribute("data-ora")&&(-1===e[m].src.indexOf("enablejsapi")&&(-1===
e[m].src.indexOf("?")?e[m].src+="?enablejsapi\x3d1":e[m].src+="\x26enablejsapi\x3d1"),d(e[m]))},d=function(e){var m=k.length;k[m]=new q(e,m);f(e)&&e.setAttribute("data-ora","ytBound");f(e)?ORA.Debug.debug("YT - adding player number "+m+" - binding to "+e.src,"YT_PLUGIN"):ORA.Debug.debug("YT - adding player number "+m+" - binding to manual player object","YT_PLUGIN");"function"===typeof u.addPlayerCallback&&u.addPlayerCallback(e)},f=function(e){return"object"===typeof HTMLElement?e instanceof HTMLElement:
e&&"object"===typeof e&&1===e.nodeType&&"string"===typeof e.nodeName},q=function(e,m,x){var l=this,p={id:m,ready:!1,loaded:!1,info:{playerState:null,currentTime:null,duration:null,videoData:{video_id:null,video_author:"",title:"",list:null},isMuted:!1,volume:null,videoUrl:"",playbackQuality:null,playlist:null,playlistIndex:-1}},h=null,n=function(t){var y=g.getVideoData();p.info.videoData.video_id=y.video_id;p.info.videoData.title=y.title;p.info.videoData.author=y.author;p.info.duration=g.getDuration();
p.info.currentTime=g.getCurrentTime();p.info.playerState=g.getPlayerState();p.info.playlist=g.getPlaylist();p.info.playlistIndex=g.getPlaylistIndex();p.info.muted=g.isMuted();p.info.volume=g.getVolume();p.info.playbackQuality=g.getPlaybackQuality();p.info.videoUrl=g.getVideoUrl();t&&(videoEventFn(l.videoStates,p,"updatemeta"),videoEventFn(l.videoStates,p,"load"))},z=function(){p.info.currentTime=g.getCurrentTime();g.isMuted()!==p.info.isMuted&&(p.info.isMuted=g.isMuted(),videoEventFn(l.videoStates,
p,"mute"));g.getVolume()!==p.info.volume&&(p.info.volume=g.getVolume(),videoEventFn(l.videoStates,p,"volume"));g.getPlayerState()!==p.info.playerState&&(ORA.Debug.debug("YT discovered missing change event - resending "+p.info.videoData.title+" - Last State:"+p.info.playerState+" current state:"+g.getPlayerState(),"YT_PLUGIN"),window["ORA_YTStateChange"+p.id]({target:g,data:g.getPlayerState()}));videoEventFn(l.videoStates,p,"timeupdate")};var g=f(e)?new YT.Player(e):e;l.videoStates={WT:{clip_n:null,
clip_id:null,clip_secs:null,clip_mins:null,clip_ct:null,clip_perc:null,clip_ev:null,clip_duration:null,clip_t:null,clip_player:"youtube",clip_provider:null,clip_vol:null,clip_res:null,clip_player_res:null,clip_duration_n:null,clip_tv:"2.0.0",clip_mode:null,dl:40},_state:"loading",_lastBeacon:0,_eventThrottle:0,_lastQuartile:0,_pauseDelay:null,_currentQuartile:0,_pauseTime:null,_hasPlayed:!1};l.isReady=function(){return p.ready};g.oraId=m;videoEventFn=x?x:r;window["ORA_YTReady"+m]=function(t){ORA.Debug.debug("YT Player ready for "+
t.target.getVideoData().title,"YT_PLUGIN");n(!0);h||(h=setInterval(z,100));p.ready=!0};g.addEventListener("onReady","ORA_YTReady"+m);window["ORA_YTStateChange"+m]=function(t){var y=t.target.getVideoData(),A="unstarted ended play pause buffering undefined cued".split(" "),B=p.info.playerState;t.data!==YT.PlayerState.PAUSED&&(p.info.currentTime=g.getCurrentTime());ORA.Debug.debug("YT "+y.title+" State Change to "+A[t.data+1]+" from "+A[p.info.playerState+1],"YT_PLUGIN");p.info.playerState=t.data;(t.data===
YT.PlayerState.UNSTARTED||B===YT.PlayerState.UNSTARTED&&t.data===YT.PlayerState.BUFFERING)&&n(t.data===YT.PlayerState.BUFFERING);t.data===YT.PlayerState.ENDED||t.data===YT.PlayerState.UNSTARTED&&B!==YT.PlayerState.CUED?(h&&clearInterval(h),h=null,p.loaded=!1):h||h||(h=setInterval(z,100));ORA.Debug.debug("YT "+y.title+" videoEventCallback "+A[t.data+1]+" at "+g.getCurrentTime(),"YT_PLUGIN");videoEventFn(l.videoStates,p,A[t.data+1])};g.addEventListener("onStateChange","ORA_YTStateChange"+m);window["ORA_YTError"+
m]=function(t){ORA.Debug.debug("YT Player error for "+t.target.getVideoData().title,"YT_PLUGIN");p.error=t.data;videoEventFn(l.videoStates,p,"error")};g.addEventListener("onError","ORA_YTError"+m);l.getMeta=function(){return p};l.player=g;l.getProgressEventId=function(){return h};l.reset=function(){h&&clearInterval(h);h=null;delete window["ORA_YTError"+p.id];delete window["ORA_YTStateChange"+p.id];delete window["ORA_YTReady"+p.id]}},u={load:!0,loadMeta:!0,pause:!0,quartile:!0,beacon:!0,seek:!0,beaconRate:30,
pctInc:25,volume:!0,buffering:!0,cued:!0,mute:!0,bins:15,poll:!1,pollRate:500,screenMode:!0,trackCallback:function(e){ORA.click({data:e.args})},loadAPI:!1,mode:"automatic",pollId:null},w=function(e,m){var x,l=e.config||{};window.ORA&&ORA.Debug.info("YouTube Plugin Init Started","YT_PLUGIN");try{if(!window.postMessage){ORA.Debug("YT - Browser does not support postMessage which is required for YouTube tracking - exiting","YT_PLUGIN");m&&m();return}for(x in l)l.hasOwnProperty(x)&&void 0!==l[x]&&(u[x]=
l[x]);if(void 0!==u.enable&&!u.enable){ORA.Debug.info("YT loading is disabled plugin","YT_PLUGIN");return}window.YT&&window.YT.Player?v():(ORA.Debug.debug("YT - defering init, the youtube iframe_api script has not loaded"),b());if(u.loadAPI&&!window.YT){ORA.Debug.info("YT loading iframe_api plugin","YT_PLUGIN");var p=document.createElement("script");p.src="//www.youtube.com/iframe_api";var h=document.getElementsByTagName("script")[0];h.parentNode.insertBefore(p,h)}}catch(n){window.ORA&&(ORA.Debug.info("YT Plugin Init Error",
"YT_PLUGIN"),m&&m())}window.ORA&&ORA.Debug.info("YT Plugin Init Complete","YT_PLUGIN");m&&m()},v=function(){"automatic"===u.mode||"auto"===u.mode?(ORA.Debug.info("YT configuring for automatic mode","YT_PLUGIN"),c()):ORA.Debug.info("YT configuring for manual mode","YT_PLUGIN");u.poll&&(ORA.Debug.info("YT polling for videos","YT_PLUGIN"),u.pollId=setTimeout(function(){c()},u.pollRate));ORA.Debug.info("YT Plugin Init Complete","YT_PLUGIN")},r=function(e,m,x){var l=u;var p=m.info;var h=m.info.videoData;
"timeupdate"!==x&&window.ORA&&window.ORA.Debug.debug("YT Plugin player event received: "+x+" for "+e.WT.clip_n,"YT_PLUGIN");p.playlist&&(e.WT.clip_playlist_items=p.playlist.length,-1!==p.playlistIndex&&(e.WT.clip_playlist_index=p.playlistIndex));var n=!1;switch(x){case "play":e._pauseDelay&&(clearTimeout(e._pauseDelay),e._pauseDelay=null,1.2<Math.abs(e._pauseTime-p.currentTime)?(r(e,m,"seek"),e._state=x):r(e,m,"sendpause"));if("play"===e._state)break;if("seek"===e._state){e._state=x;break}"pause"===
e._state?l.pause&&(e.WT.clip_ev="Resume",n=!0):("loading"===e._state&&(r(e,m,"load"),r(e,m,"meta")),r(e,m,"meta"),e.WT.clip_ev="Play",e._lastBeacon=0,e.WT.clip_perc=null,e.WT.clip_secs=null,e.WT.clip_mins=null,e._currentQuartile=0,e._lastQuartile=0,e._hasPlayed=!0,n="play"!==e._state);e._state=x;break;case "pause":e._pauseTime=p.currentTime;e._pauseDelay||"seek"===e._state||(e._pauseDelay=setTimeout(function(){e._pauseDelay=null;r(e,m,"sendpause")},2E3));break;case "sendpause":l.pause&&(n=!0);e._state=
"pause";e.WT.clip_ev="Pause";break;case "ended":if("compete"===e._state||!e._hasPlayed){e._state="complete";break}m.info.currentTime=m.info.duration;r(e,m,"timeupdate");e.WT.clip_ev="Complete";e._hasPlayed=!1;n=!0;e._state=x;break;case "buffering":e._pauseDelay?(clearTimeout(e._pauseDelay),e._pauseDelay=null,r(e,m,"seek"),l.buffering&&(e.WT.clip_ev="Buffering",n=!0,e._state="seek")):l.buffering&&(e.WT.clip_ev="Buffering",n=!0,e._state=x);break;case "unstarted":r(e,m,"updatemeta");e._lastBeacon=0;
e.WT.clip_perc=null;e.WT.clip_secs=null;e.WT.clip_mins=null;e._currentQuartile=0;e._lastQuartile=0;e.WT.dl=40;break;case "cued":l.cued&&(e.WT.clip_ev="Cued",n=!0,e._state=x);break;case "timeupdate":e.WT.clip_secs=Math.floor(100*p.currentTime)/100;e.WT.clip_mins=Math.floor(100*p.currentTime/60)/100;e.WT.clip_vol=Math.floor(p.volume);0<p.duration&&0<p.currentTime&&(e.WT.clip_perc=Math.floor(p.currentTime/p.duration*100));if(0===e._eventThrottle&&l.beacon&&p.currentTime>e._lastBeacon+l.beaconRate){e.WT.clip_ev=
"Beacon";n=!0;e._lastBeacon=p.currentTime+l.beaconRate;break}if(l.quartile&&(e.WT.clip_perc||0)>=e._lastQuartile+l.pctInc){e._currentQuartile=Math.floor(e.WT.clip_perc/l.pctInc)*l.pctInc;e._currentQuartile>e._lastQuartile+l.pctInc&&(p=JSON.parse(JSON.stringify(e)),p._currentQuartile-=l.pctInc,r(p,m,"quartile"));r(e,m,"quartile");break}0<a.length&&l.trackCallback(a.shift());0<e._eventThrottle&&e._eventThrottle--;break;case "quartile":e.WT.clip_perc=e._currentQuartile;e._lastQuartile=e._currentQuartile;
e.WT.clip_ev="Quartile";n=!0;break;case "seek":if(0===p.currentTime&&"play"!==e._state){e._state="Ended";break}e._lastBeacon=p.currentTime;"ended"!==e._state&&l.seek&&0===e._eventThrottle&&0!==p.currentTime&&l.seek&&(e.WT.clip_ev="Seek",n=!0);e._state="seek";e._eventThrottle=10;break;case "load":m.loaded||(l.load&&(e.WT.clip_ev="Load",e.WT.dl=40,n=!0),e._lastBeacon=0,e.WT.clip_perc=null,e.WT.clip_secs=null,e.WT.clip_mins=null,e._currentQuartile=0,e._lastQuartile=0,e._state=x,m.loaded=!0);break;case "mute":l.mute&&
(e.WT.clip_ev=p.isMuted?"Mute":"UnMute",n=!0);e._state=x;break;case "meta":r(e,m,"updatemeta");m.loaded||r(e,m,"load");l.loadMeta&&(e.WT.clip_ev="Loadedmetadata",n=!0);break;case "updatemeta":isFinite(p.duration)?(e.WT.clip_duration=Math.floor(100*p.duration)/100,e.WT.clip_duration_min=Math.floor(100*p.duration/60)/100,e.WT.clip_mode="FixedDuration"):(l.quartile=!1,e.WT.clip_mode="Stream");l.bins&&isFinite(p.duration)&&(n=Math.floor((p.duration+l.bins)/l.bins),e.WT.clip_duration_n=(n-1)*l.bins+"-"+
n*l.bins);p.videoUrl?(e.WT.clip_src=p.videoUrl,e.WT.clip_ct="youtube",1<p.videoUrl.match(/:\/\/(www\.)?(.[^/:]+)/).length?e.WT.clip_provider=p.videoUrl.match(/:\/\/(www\.)?(.[^/:]+)/)[2]:e.WT.clip_provider="unknown"):(e.WT.clip_ct="unknown",e.WT.clip_provider="self");e.WT.clip_n=h.title?h.title:p.videoUrl?p.videoUrl.split("/").pop().split(".")[0]:"unknown";h.video_id&&(e.WT.clip_id=h.video_id);p.playerType&&(e.WT.clip_t=p.playerType);p.playbackQuality&&(e.WT.clip_res=p.playbackQuality);e.WT.clip_vol=
Math.floor(p.volume);n=!1;break;case "volume":l.volume&&0===e._eventThrottle&&(e.WT.clip_vol=Math.floor(p.volume),e.WT.clip_ev="Volume",n=!0,e._eventThrottle=20);break;case "error":switch(m.error){case 2:e.WT.clip_ev="Error - request contains invalid parameter";break;case 5:e.WT.clip_ev="Error - Content can not be played in a H%ML5 Player";break;case 100:e.WT.clip_ev="Error - Requested video was not found";break;case 101:case 102:e.WT.clip_ev="Error - Video can not be played in embeded players";break;
default:e.WT.clip_ev="Error - Unknown video error"}e.WT.dl=42;n=!0}if(n){window.ORA&&window.ORA.Debug.debug("YT Plugin queueing data for "+e.WT.clip_n+" : "+e.WT.clip_ev,"YT_PLUGIN");n={};p=Object.keys(e.WT);for(h=0;h<p.length;h++)"number"===typeof e.WT[p[h]]?n["WT."+p[h]]=e.WT[p[h]].toString():null===e.WT[p[h]]?delete n["WT."+p[h]]:n["WT."+p[h]]=e.WT[p[h]];a.push({element:this,args:n,transform:l.transformCallback,data:e.WT});if("function"===typeof l.trackCallback)try{l.trackCallback(a.pop())}catch(z){window.ORA&&
ORA.Debug.info("YT Plugin Error with trackCallback","YT_PLUGIN")}}e.WT.dl=41};ORA.analytics.plugins||(ORA.analytics.plugins={});ORA.analytics.plugins.yt||(ORA.analytics.plugins.yt={});ORA.analytics.plugins.yt.init=w;ORA.analytics.plugins.yt.reset=function(){for(var e in k)k.hasOwnProperty(e)&&k[e].reset();u.pollId&&(clearInterval(u.pollId),u.pollId=null);k=[]};ORA.analytics.plugins.yt.ytVideoClass=q;ORA.analytics.plugins.yt.videoEventCallback=r;ORA.analytics.plugins.yt.getConfig=function(){return u};
ORA.analytics.plugins.yt.setConfig=function(e){u=e};ORA.analytics.plugins.yt.addPlayer=d;ORA.Debug.debug("YouTube Plugin registration start","ANA");ORA.regPlugin("yt",w)})();
(function(){var k={readCookies:[],enable:!0},a={},b={},c,d=function(w,v,r){-1<w.indexOf(v.parseOn||":")||-1<w.indexOf(v.parseLv||"\x3d")?w.split(v.parseOn||":").forEach(function(e){c[r]||(c[r]={});c[r][e.substr(0,e.indexOf(v.parseLv||"\x3d"))]=e.substr(e.indexOf(v.parseLv||"\x3d")+1)}):c[r]=w},f=function(w,v,r){var e=!0;r&&void 0!==r.persist&&(e=r.persist);e?a[v]=w:b[v]=w},q=function(w){for(var v in a)a.hasOwnProperty(v)&&w.setParam(v,a[v]);if("seed message"===w.desc)for(var r in b)b.hasOwnProperty(r)&&
w.setParam(r,b[r])},u=function(w){for(var v in k)k.hasOwnProperty(v)&&void 0!==w[v]&&(k[v]=w[v])};ORA.Debug.info("cookie cutter start registration","ANA-cookieCutter");ORA.regPlugin("cookieCutter",function(w,v){ORA.Debug.info("cookie cutter start init","ANA-cookieCutter");var r=v||function(){},e=ORA.getIEVer();if(e&&9>e)return ORA.Debug.info("requires \x3e\x3d ie9, disabling plugin","ANA-cookieCutter"),r();u(w.config);if(!k.enable)return ORA.Debug.info("cookie cutter is disables","ANA-cookieCutter"),
r();Object.values||(Object.values=function(m){var x=[],l;for(l in m)m.hasOwnProperty(l)&&x.push(m[l]);return x});k.readCookies.forEach(function(m){var x=Object.keys(m.cookie).shift(),l=Object.values(m.cookie).shift(),p=m.options;c||(c={});if(void 0===c[x]){var h=document.cookie.split(";");p=p||{};for(var n=h.length-1;0<=n;n--){var z=h[n].substr(0,h[n].indexOf("\x3d")).replace(/^\s+|\s+$/g,""),g=h[n].substr(h[n].indexOf("\x3d")+1);x&&z===x&&d(g,p,z)}}h=c[x]||"";ORA.Debug.debug("cookieCutter looking at: "+
x);if(h)if(m=m.options,"object"===typeof h)for(var t in h)h.hasOwnProperty(t)&&void 0!==l[t]&&(f(h[t],l[t],m),ORA.Debug.debug("cookie cutter found target "+l[t]+"\x3d"+h[t]+" - "+JSON.stringify(m)));else f(h,l,m),ORA.Debug.debug("cookie cutter found target "+h+"\x3d"+l+" - "+JSON.stringify(m))});ORA.analytics.addMutation("cookiecutter",q);ORA.Debug.info("cookie cutter complete init","ANA-cookieCutter");return r()});ORA.Debug.info("cookie cutter start registration complete","ANA-cookieCutter");ORA.analytics.plugins.cookieCutter=
{};ORA.analytics.plugins.cookieCutter.testNode=function(w){return eval(w)};ORA.analytics.plugins.cookieCutter.t1=function(){return k};ORA.analytics.plugins.cookieCutter.t2=function(){return c};ORA.analytics.plugins.cookieCutter.t3=function(){return{persist:a,session:b}};ORA.analytics.plugins.cookieCutter.t3=function(){a={};b={}}})();
(function(){var k,a,b,c,d={enable:!0,cookieDays:365,cookieName:"ORAPERSIST",cookieDomain:"",params:"dcsvid infy riid rid customer_id elqCID elq_cid elq_mid product".split(" "),defPrefix:"DCSext",priority:100,useMostRecent:!0,lowerCaseValues:!0},f=new function(){var v=this;v.getQueryParamsMap=function(r,e){var m=ORA.common.extendObject({}),x=[],l=r,p=e||d;try{m=JSON.parse(r)}catch(g){"string"===typeof l&&(l=l.replace(/^[&\?\s]+/i,""),x=l.split("\x26"));for(var h=0,n=x.length;h<n;++h){l=x[h];l=l.split("\x3d");
var z=l[0].toLowerCase();""!==z&&(m[z]=p.lowerCaseValues?decodeURIComponent(l[1].toLowerCase()):decodeURIComponent(l[1]))}}return m};v.getValueOfExistingParam=function(r,e,m,x,l){var p=null,h,n=l||d;r.forEach(function(z,g){if(g.toLowerCase()===m||g.toLowerCase()===e)h=n.lowerCaseValues&&"string"===typeof z?z.toLowerCase():z});h?(p=h,ORA.Debug.debug("Taking current value from QRY: "+m+'\x3d"'+p+'"',"ANA - pp")):null!==x.getParam(m)&&(p=x.getParam(m),ORA.Debug.debug("Taking current value from dcsMsg: "+
m+'\x3d"'+p+'"',"ANA - pp"));p&&ORA.Debug.debug("Param (current value): "+m+'\x3d"'+p+'"',"ANA - pp");return p};v.getParamValue=function(r,e,m,x,l){r=v.getValueOfExistingParam(r,e,m,x);m=v.getQueryParam(l,m);null===r||"undefined"===r||!d.useMostRecent&&null!==m||(m=r);return m};v.getQueryParam=function(r,e){var m=null;r.forEach(function(x,l){l.toLowerCase()===e&&(m=x)});return m};v.applyPreviouslyPersistedParamsValues=function(r,e,m){for(var x="",l=ORA.common.extendObject({}),p=0,h=d.params.length;p<
h;++p){var n=d.params[p],z=n;ORA.Debug.info("Processing param: "+n,"ANA - pp");e[n]=v.getParamValue(r,n,z,m,e);var g=v.getQueryParam(e,n);g&&(ORA.Debug.info("Overriding MSG value with saved value: "+z+'\x3d"'+g+'"',"ANA - pp"),m.setParam(z,g,!0),l[z]=g);(z=v.getQueryParam(r,n)||v.getQueryParam(r,z))&&ORA.common.QueryParamCache.set(n,z)}l.forEach(function(t,y){x=x+"\x26"+y+"\x3d"+encodeURIComponent(t)});return x=x.replace(/^[&\?\s]+/i,"")};v.arrayIndexOf=function(r,e){if(!ORA.analytics.isArray(r))return-1;
if(Array.prototype.indexOf)return r.indexOf(e);for(var m=0,x=r.length;m<x;m++)if(r[m]===e)return m;return-1}},q=function(){this.getCookieDomain=function(){var v="",r=d.cookieDomain;r==location.hostname&&(r="");b&&b.FPCConfig&&b.FPCConfig.domain&&(v=b.FPCConfig.domain);ORA.Debug.debug("sDCSDomain: "+v,"ANA - pp");r&&"."===r.charAt(0)&&(r=r.slice(1));return d.cookieDomain?r:v?v:ORA.cookieMgr.checkCookieOnDomainAndGetTLDomain()}},u=function(){this.savePersistedParams=function(v,r,e,m){var x=new Date;
x.setDate(x.getDate()+m);m=";domain\x3d"+e+";path\x3d/;expires\x3d"+x.toUTCString();e||(m=";path\x3d/;expires\x3d"+x.toUTCString());k(v,r,m)};this.getPersistedParams=function(v){var r=ORA.common.extendObject({});v=a(v);return null===v?r:r=f.getQueryParamsMap(v)}};var w=new function(){var v=this,r=new q,e=new u;v.ppMutation=function(m){var x=ORA.common.QueryParamCache.getCache(),l=e.getPersistedParams(d.cookieName);ORA.Debug.debug("QRY params: "+JSON.stringify(x),"ANA - pp");m=f.applyPreviouslyPersistedParamsValues(x,
l,m);c||(c=r.getCookieDomain(),ORA.Debug.debug("Cookie domain to use: "+c,"ANA - pp"));ORA.Debug.debug("Saving persistent params in cookie: "+d.cookieName+'\x3d"'+m+'"',"ANA - pp");e.savePersistedParams(d.cookieName,m,c,d.cookieDays)};v.ppInit=function(m,x){var l=m.config;if(l){for(var p in l)l.hasOwnProperty(p)&&(d[p]=l[p]);l=[];p=0;for(var h=d.params.length;p<h;++p)d.params[p]=d.params[p].toLowerCase(),l.push(d.params[p]);d.params=l}ORA.Debug.info("initializing...","ANA - pp");d.enable?d.params&&
0!==d.params.length?(ORA.Debug.debug("params to persist: "+d.params.join(", "),"ANA - pp"),k=ORA.analytics.setCookie,a=ORA.analytics.getCookieRaw,b=ORA.analytics.dcsRef,ORA.analytics.addMutation("persistParams",v.ppMutation,3)):ORA.Debug.debug("no persist params defined - will not run","ANA - pp"):ORA.Debug.debug("disabled in config - will not run","ANA - pp");d.blockCollect&&x&&x()}};ORA.regPlugin("pp",w.ppInit);ORA.plugins||(ORA.plugins={});ORA.plugins.pp||(ORA.plugins.pp={});ORA.Debug.debug("PP: Plugin initialized",
"ANA - pp");ORA.plugins.pp.Domain=new q;ORA.plugins.pp.PersistParams=new u;ORA.plugins.pp.OraclePP=w;ORA.plugins.pp.helper=f;ORA.plugins.pp.config=d})();ORA.Debug.debug("PP: Loading Plugin","ANA");
(function(){var k={cgDefs:["wt.cg_n","wt.cg_s","wt.cg_s#"],urlData:window.location.pathname.split("/"),init:function(a,b){var c=a.config||{},d=b||function(){};c.cgDefs&&(k.cgDefs=c.cgDefs);if(void 0===c.enable||c.enable){for(c=0;c<k.urlData.length;){if(""===k.urlData[c]||-1<k.urlData[c].indexOf("."))k.urlData.splice(c,1),c--;c++}ORA.Debug.debug("cg URL parsing is "+JSON.stringify({urlData:k.urlData},null,4),"ANA-cg");ORA.analytics.addMutation("addCg",k.addCgMutation);d();ORA.Debug.debug("cg Plugin init complete",
"ANA-cg")}else ORA.Debug.debug("content group plugin is disabled, exiting","ANA-cg"),d()},addCgMutation:function(a){try{for(var b=k.cgDefs||[],c=0;(c<b.length||-1<b[b.length-1].indexOf("#"))&&c<k.urlData.length;c++)c>=b.length-1&&-1<b[b.length-1].indexOf("#")?a.payload[b[b.length-1].replace("#",c)]=k.urlData[c]:a.payload[b[c]]=k.urlData[c]}catch(d){ORA.Debug.debug("cg Plugin mutation error","ANA-cg")}},rmCgMutation:function(){ORA.analytics.rmMutation("addCg")}};ORA.Debug.debug("cg - Registering Plugin",
"ANA-cg");ORA.regPlugin("cg",k.init,{blockCollect:!0});ORA.analytics.plugins||(ORA.analytics.plugins={});ORA.analytics.plugins.cg||(ORA.analytics.plugins.cg={});ORA.analytics.plugins.cg.addCg=k})();ORA.setExecuteState("analytics","ready");ORA.fireEvent(new ORA.Event(ORA.Event.ANA_LOAD_COMPLETE,ORA.Event.STATUS_SUCCESS),!0);