/*
 Copyright © 1995, 2021, Oracle and/or its affiliates. All rights reserved.

 For information, please see the following link:
 https://www.oracle.com/legal/copyright.html

 Oracle Infinity
 @preserve Copyright (c) 2017, 2018, 2019, Oracle and/or its affiliates. All rights reserved.
 odc.js v1.0.7
 Created: 2023-11-14T12:16:27+0000

*/
(function(){function m(t,r){var v={major:1,minor:0,inc:7},h=this,B=!1,C=2E3,z="sizzle",O=null,P=!1,E=!1,K=!1,k={};this.getTagId=function(){return"oracle"};this.inHead=function(){return E};this.applyStyleSheet=function(a,b){try{var c=r.getElementsByTagName("head")[0],d=r.createElement("style");d.type="text/css";d.id=b;d.styleSheet?d.styleSheet.cssText=a:d.appendChild(r.createTextNode(a));c.appendChild(d)}catch(f){ORA.Debug.error("applyStyleSheet:  Failed to failed to apply stylesheet","004",f)}};this.removeStyleSheet=
function(a){try{var b=r.getElementById(a);"undefined"!==typeof b&&null!==b&&b.parentNode.removeChild(b)}catch(c){ORA.Debug.debug("removeStyleSheet:  Failed to remove stylesheet")}};this.getSelector=function(){if("sizzle"===z){if("undefined"!==typeof Sizzle&&ORA.hasVal(Sizzle))return Sizzle;if("undefined"!==typeof ORA.Sizzle)return ORA.Sizzle}else{if(null!==O)return O;ORA.Debug.error("getSelector:  No Selector found","003")}return!1};this.setCustomSelector=function(a,b){z=a;O=b};this.hasVal=function(a){return null!==
a&&"undefined"!==typeof a};var W=function(a,b,c){a=h.hasVal(a)&&"shift"!==b&&!E;b=h.hasVal(b);c=h.hasVal(c);return a&&b&&c},X=function(a,b,c){var d="hideAndShow:  ";d=E?d+"tag inHead":d+"tag not inHead";d=c?d+", showing":d+", hiding";d=a&&a.nodeName?d+(", "+a.nodeName):d+", unnamed elem";return d+('"  with type "'+b+' "')},Y=function(a,b,c){E?a("body{ display: none !important}"):(b.style.display="",c&&(b.style.display="none"),b===r.body||c||(r.body.style.display=""))},Z=function(a,b,c){E?a("body{ visibility: hidden !important}"):
(b.style.visibility="visible",c||(b.style.visibility="hidden"),b.style.hidden=!c,b===r.body||c||(r.body.style.visibility="visible",r.body.style.hidden=!1))},aa=function(a,b,c){c?(a=r.getElementById("ora_shiftStyle"))&&a.parentNode.removeChild(a):(a=r.getElementsByTagName("head")[0],b=r.createElement("style"),b.type="text/css",b.id="ora_shiftStyle",b.styleSheet?b.styleSheet.cssText="body{position:absolute !important; left: -1000% !important; visibility: hidden}":b.appendChild(r.createTextNode("body{position:absolute !important; left: -1000% !important;}")),
a.appendChild(b))},ba=function(a,b,c,d){b=r.getElementById("ora_overlay");var f=r.getElementById("ora_overlayStyle");a=d;h.hasVal(d)&&(a="#ffffff");c&&b?(b.parentNode.removeChild(b),f&&f.parentNode.removeChild(f)):c||b||(E&&h.Debug.error("hideAndShow: Warning! tag detected in head, overlay mode may error out or cause flickering","007"),f||(c=r.createElement("style"),c.setAttribute("type","text/css"),c.setAttribute("id","ora_overlayStyle"),a="#ora_overlay{position:absolute;width:100%;height:100%;top:0px;right:0px;bottom:0px;left:0px;background-color:"+
(a+";z-index:2147483646}"),c.styleSheet?c.styleSheet.cssText=a:c.appendChild(r.createTextNode(a)),r.getElementsByTagName("head")[0].appendChild(c)),h.hasVal(d)?b=r.createElement("div"):(b=r.createElement("iframe"),b.frameBorder=0),b.id="ora_overlay",r.getElementsByTagName("body")[0].appendChild(b))};this.hideAndShow=function(a,b,c){try{if(W(a,b,c)){h.Debug.debug(X(a,b,c));var d=function(f){c?h.removeStyleSheet("o_style"):h.applyStyleSheet(f,"o_style")};switch(b){case "display":Y(d,a,c);break;case "visibility":Z(d,
a,c);break;case "shift":case "supershift":aa(d,a,c);break;case "overlay":ba(d,a,c);break;case "none":ORA.Debug.trace("LOADER: type: none");break;default:h.Debug.debug("hideAndShow did not contain a matching type, so not hiding/showing")}d={};d.displayType=b;d.display=c;h.fireEvent(new ORA.Event(ORA.Event.HIDESHOW,ORA.Event.STATUS_SUCCESS,a,d))}else h.Debug.error("hideAndShow param list incomplete","006")}catch(f){h.Debug.error("Failure in hide/show functionality.  Verify valid HTML syntax","008",
f)}};E=function(){try{var a=r.getElementsByTagName("script");return"HEAD"===a[a.length-1].parentNode.nodeName}catch(b){return WT.Debug.error("inHead: Failed to detect if in head, assuming inHead","001",b),!0}}();var D=function(){P||(P=!0,ORA.fireEvent(new ORA.Event(ORA.Event.DOM_READY,ORA.Event.STATUS_SUCCESS),!0))},L=function(){K||(K=!0,ORA.fireEvent(new ORA.Event(ORA.Event.DOM_ONLOAD,ORA.Event.STATUS_SUCCESS),!0))},R=function(a){for(var b=document.cookie.split(";"),c=0;c<b.length;c++){var d=[];
d[0]=b[c].substring(0,b[c].indexOf("\x3d"));for(d[1]=b[c].substring(b[c].indexOf("\x3d")+1);" "===d[0].charAt(0);)d[0]=d[0].substring(1,d[0].length);if(d[0]===a)return d[1]}return null},S=function(a){for(var b=document.getElementsByTagName("meta"),c=0;c<b.length;c++)if(b[c].name===a)return b[c].content;return null};this.execute=function(a){Array.prototype.slice.call(arguments,1);fireEventName(ORA.Event.LOADER_PRE_EXECUTE,a);fireEventName(ORA.Event.LOADER_EXECUTE,a)};this.loaderConversionTimeoutDefault=
function(){return C};this.setLoaderConversionTimeoutDefault=function(a){C=a};this.reset=function(){for(var a in k)k.hasOwnProperty(a)&&k[a].reset();fireEventName(ORA.Event.LOADER_RESET,null)};this.pollForCondition=function(a,b,c){var d=200,f=function(g,e,q,n,u){window.setTimeout(function(){d--;g()?(h.Debug.trace("pollForCondition success result\x3d"+g(),"LOADER"),h.Debug.superfine("pollForCondition success condition\x3d"+g.toString(),"LOADER"),e&&(e(),h.Debug.trace("pollForCondition running callback",
"LOADER"),h.Debug.superfine("pollForCondition callback\x3d"+e.toString(),"LOADER"))):0<d?(h.Debug.trace("LOADER:  pollForCondition timeoutCount\x3d"+d),f(g,e,q,d)):(h.Debug.error("pollForCondition Fail on "+g.toString(),"009"),q&&(q(),h.Debug.superfine("pollForCondition callbackFailure\x3d"+q.toString(),"LOADER")))},u)};f(a,b,c,d,5)};this.paramsMerge=function(a,b,c){var d={};if(ORA.hasVal(a))for(var f in a)a.hasOwnProperty(f)&&(d[f]=a[f]);for(var g in b)ORA.hasVal(b[g])&&b.hasOwnProperty(g)&&(ORA.hasVal(c)&&
ORA.hasVal(c[g])?d[g]=c[g]:d[g]=b[g]);return d};this.downloadLib=function(a,b,c,d,f,g){g&&(h.Debug.info("LOADER:  Start download: https:"+g+" \x26 attach to "+a+", async\x3d"+f),window.setTimeout(function(){var e=r.getElementsByTagName(a)[0],q=r.createElement("script");q.type="text/javascript";q.src="https:"+g;q.setAttribute("async",f);q.setAttribute("defer",f);q.oraHasRun=!1;var n=function(){!1===this.oraHasRun?(b(),this.oraHasRun=!0,h.Debug.info("Completed download: https:"+g+", callback running oraHasRun\x3d"+
this.oraHasRun,"LOADER"),h.Debug.superfine("downloadLib: successCallback\x3d"+b.toString(),"LOADER")):h.Debug.trace("downloadLib: not running successCallback, since oraHasRun\x3d"+this.oraHasRun,"LOADER")};b&&(q.onload=n,q.onreadystatechange=n);q.onerror=function(){h.Debug.error("FAILED download: https:"+g+" \x26 attach to "+a+", async\x3d"+f,"010");c&&(c(),h.Debug.superfine("failCallback: "+c.toString(),"LOADER"))};"undefined"!==typeof e?e.appendChild(q):h.Debug.info("LOADER:  Dom element: "+a+" is not found so not Downloading")},
d))};this.downloadLibs=function(a,b,c,d,f){if("undefined"===typeof f)h.Debug.info("LOADER:  downloadLibs srcs is empty");else{var g={},e=function(n){return function(){g[n]="complete";h.Debug.trace("LOADER:  downloadLibs is complete src:"+n+" \x3d "+f[n])}},q;for(q in f)f.hasOwnProperty(q)&&(g[q]="waiting",h.Debug.trace("LOADER:  downloadLibs is waiting on src:"+q+" \x3d "+f[q]),h.downloadLib(a,e(q),null,c,d,f[q]));h.pollForCondition(function(){for(var n in g)if(g.hasOwnProperty(n)&&"complete"!==g[n])return!1;
return!0},function(){h.Debug.debug("LOADER:  downloadLibs completed on all downloads");b()})}};this.parseQueryString=function(a){var b=a;h.hasVal(a)&&h.hasVal(a.location)&&h.hasVal(a.location.search)||(b=document);a=function(c){var d=c.split("\x26"),f={};null!==d&&0===d.length&&(d=c.split(";"));if(null===d)return f;c=0;d&&(c=d.length-1);for(var g=0;g<=c;g++){var e=d[g].split("\x3d");e[0]=unescape(e[0]);e[1]=unescape(e[1]);e[0]=e[0].replace(/\+/g," ");e[1]=e[1].replace(/\+/g," ");e[1]=e[1].replace(/<.*\?>/g,
"");f[e[0]]=e[1]}return f};return b.location.search?(b=b.location.search.substring(1,b.location.search.length),a(b)):b.location.href?(b=b.location.href.split("?"),2===b.length?a(b[1]):null):null};this.abortModuleHelper=function(a,b){ORA.fireEvent(new ORA.Event(a+"_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS));ORA.setExecuteState(a,ORA.Event.LOADER_MODULE_ABORT);ORA.Debug.error("Aborting product: "+a,"011");ORA.Debug.error("LOADER Error","011",b)};this.Event=function(a,b,c,d){a&&(a=a.toLowerCase());
this.name=a;this.handler=null;this.state=ORA.Event.STATUS_UNKNOWN;b&&(this.state=b);this.target=c;this.params={};d&&(this.params=d)};this.fireEventName=function(a,b){ORA.fireEvent(new ORA.Event(a,ORA.Event.STATUS_SUCCESS,null,b),null,null,!0)};this.EventEngineClass=function(){var a={},b={},c=function(g,e,q,n){B&&!n&&h.Debug.error("fireEvent: Loader global abort, Aborted due to prior error","012",null,"LOADER");e.handler=g;e.params.eventID=(new Date).getTime();n="not set";q&&(n=q);h.Debug.trace("fireEvent: [name: "+
e.name+"], state:"+e.state+"async["+n+"]","LOADER");h.Debug.superfine("function:"+e.handler.toString()+"]","LOADER");q?window.setTimeout(function(u,w){return function(){u(w)}}(g,e),0):e.handler(e);return 1},d=function(g,e,q,n,u){for(var w=0;w<b[g][u].length;w++)if(h.hasVal(b[g][u][w])&&b[g][u][w].toString()===n.toString()&&!0!==e){q=!0;break}q||(b[g][u].push(n),e="addEventHandler success handler"+b[g][u].length,e+=" for "+g+"\nhandler\x3d"+n.toString(),h.Debug.superfine(e,"LOADER"));return q};a.addEventHandler=
function(g,e,q,n){var u=g;g=0;var w=!1;if(!u||!e&&!q)return h.Debug.debug("events: Can not add event handler, missing name or listeners. ","LOADER"),-1;var y=u=u.toLowerCase();b[y]||(b[y]={});b[y].success||(b[y].success=[]);b[y].fault||(b[y].fault=[]);e&&(w=d(u,n,!1,e,"success"));w||(g=1);q&&(w=d(u,n,!1,q,"fault"));w||(g+=1);n=u;if(b[n].queue&&0!==b[n].queue.length)for(u=b[n].queue.length-1;0<=u;u--)w=b[n].queue[u],e&&"success"===w.event.state?c(e,w.event,w.async,w.override):q&&"fault"===w.event.state&&
c(q,w.event,w.async,w.override),b[n].queue.splice(u,1);return g};var f=function(g,e,q){for(var n=0;n<b[g][q].length;n++)if(h.hasVal(b[g][q][n])&&b[g][q][n].toString()===e.toString())return b[g][q].splice(n,1),1;return 0};a.removeEventHandler=function(g,e,q){if(!g)return h.Debug.trace("LOADER removeEventHandler:  events: Can not remove event handler, missing event name."),-1;g=g.toLowerCase();if(!b[g])return 0;if(!e&&!q)return delete b[g],0;var n=0;e&&(n+=f(g,e,"success"));q&&(n+=f(g,q,"fault"));return n};
a.fireEvent=function(g,e,q,n){if(B&&!q)return h.Debug.error("fireEvent: Loader global abort, Aborted due to prior error","012",null,"LOADER"),g.name?h.Debug.error("fireEvent(event\x3d"+g.name+"): g_loaderAborted due to prior error","012",null,"LOADER"):h.Debug.error("fireEvent: Aborted due to prior error, check error message for details.","012"),-1;var u=g.name,w=g.state;var y=!!b[u],F=!(!y||!b[u][w]),M=!(!y||!b[u].queue);F&&0!==b[u][w].length||!n?y?F?n=1:(h.Debug.trace("fireEvent: [name:"+u+", state:"+
w+"] no event handler was found","LOADER"),n=-1):(h.Debug.trace("fireEvent: [name: "+u+"], no registered event was found","LOADER"),n=-1):(h.Debug.trace("fireEvent: [name: "+u+"], no registered event was found, enqueueing","LOADER"),y||(b[u]={}),M||(b[u].queue=[]),b[u].queue.push({event:g,async:e,override:q}),n=0);if(0>=n)return n;n=b[u][w];for(F=y=0;F<n.length;F++)if(n[F])try{c(n[F],g,e,q),y++}catch(ca){M="Unhandled Event Exception, [name: "+u+", state: "+w+", function: ",M+=g.handler.toString()+
"]",h.Debug.error(M,"013",ca)}return y};a.getEventHandlers=function(){return b};a.length=function(){var g=0,e;for(e in b)b.hasOwnProperty(e)&&g++;return g};a.addFireOnce=function(g,e,q){var n=function(){e();a.removeEventHandler(g,n,q)};a.addEventHandler(g,n,q)};a.clearAllEventHandlers=function(){b={}};return a};var I=new this.EventEngineClass;this.addEventHandler=I.addEventHandler;this.removeEventHandler=I.removeEventHandler;this.fireEvent=I.fireEvent;this.addFireOnce=I.addFireOnce;this.clearAllEventHandlers=
I.clearAllEventHandlers;this.Event.PREINIT="preinit";this.Event.INIT="init";this.Event.PRELOAD="preload";this.Event.LOAD="load";this.Event.POSTLOAD="postload";this.Event.LOADER_ABORT="loader_abort";this.Event.LOADER_MODULE_ABORT="loader_module_abort";this.Event.DEBUGGER_CLEAR_COOKIES="debugger_clear_cookies";this.Event.DEBUGGER_DUMP_PARAMS="debugger_dump_params";this.Event.DEBUG_ERROR_OUT="debug_error_out";this.Event.DOM_READY="dom_ready";this.Event.DOM_ONLOAD="dom_onload";this.Event.TIMER_EXPIRE=
"timer_expire";this.Event.TIMER_CLEAR="timer_clear";this.Event.STATUS_SUCCESS="success";this.Event.STATUS_FAULT="fault";this.Event.STATUS_UNKNOWN="unknown";this.Event.PAGEVIEW="pageview";this.Event.CONVERSION="conversion";this.Event.DEBUGGER_CHECK_MODE="debugger_check_mode";this.Event.SCRIPT_LOAD_COMPLETE="script_load_complete";this.Event.HIDESHOW="hide_show";this.Event.SET_CLIENT_ID="set_client_id";this.Event.CLEAR_CLIENT_ID="clear_client_id";this._Debug=function(){var a=-1;this._shutdown=!1;var b=
[],c=this,d=function(f,g,e){e&&(g=e+":  "+g);if(!(a<f)&&"undefined"!==typeof console&&console){e=!0;switch(f){case 0:console.error&&(console.error(g),e=!1);break;case 1:console.warn&&(console.warn(g),e=!1);break;case 2:console.info&&(console.info(g),e=!1);break;case 3:case 4:case 5:console.log&&(console.log(g),e=!1)}!0===e&&console.log&&console.log(g)}};c.superfine=function(f,g){d(5,f,g)};c.trace=function(f,g){d(4,f,g)};c.debug=function(f,g){d(3,f,g)};c.info=function(f,g){d(2,f,g)};c.error=function(f,
g,e,q){var n="";e&&("string"===typeof e?n="\n"+e:e.toString?(n=e.toString(),e.stack&&(n+=", [stack]: "+e.stack)):n=e.message?e.name?e.fileName?"\n"+e.message+" ["+e.name+"]\n ("+e.fileName+":"+e.lineNumber+")\n"+e.stack:"\n"+e.message+" ["+e.name+"]":e.fileName?"\n"+e.message+"\n ("+e.fileName+":"+e.lineNumber+")\n"+e.stack:"\n"+e.message:e.name?e.fileName?"\n ["+e.name+"]\n ("+e.fileName+":"+e.lineNumber+")\n"+e.stack:"\n ["+e.name+"]":e.fileName?"\n\n ("+e.fileName+":"+e.lineNumber+")\n"+e.stack:
"\n");d(0,(g?g+": ":"")+f+n,q);ORA.fireEvent(new ORA.Event(ORA.Event.DEBUG_ERROR_OUT,ORA.Event.STATUS_SUCCESS,e))};c.dir=function(f,g,e){g&&d(2,g,e);console&&"function"===typeof console.dir?console.dir(f):c.dirStr(f)};c.dirStr=function(f,g){var e=f||{},q=g||"",n;for(n in e)e.hasOwnProperty(n)&&"function"!==typeof e[n]&&c.debug("\t"+n+" : "+e[n],q)};c.setDebugLevel=function(f){a=f};c.getDebugLevel=function(){return a};c.dumpParams=function(){var f=c.getConfigParams(),g;for(g in f)f.hasOwnProperty(g)&&
"object"===typeof f[g]&&c.dir(f[g],"Config parameters",g);return f};c.getConfigParams=function(){var f={};f.loader={version:v,versionStr:[v.major,v.minor,v.inc].join(".")};return f};c.checkMode=function(f){ORA.fireEvent(new ORA.Event(ORA.Event.DEBUGGER_CHECK_MODE,ORA.Event.STATUS_SUCCESS,{resetFlag:f}))};c.getHistory=function(){return b}};var T=function(a,b){this._name=a;this._state=b;this._met=!1},x=function(a,b,c){var d=this,f={},g=[];this.prodId=a;this.plugin=new b;this.executeState=x.WAITING;
this.stopTime=this.startTime=this.timer=null;this.configName="default";"undefined"!==typeof c&&(this.configName=c);this.putDependency=function(e){f[e._name]=e};this.reset=function(){d.executeState=x.WAITING;f={};g=[]};this.clearDependencies=function(){f={}};this.getDependency=function(e){for(var q in f)if(f.hasOwnProperty(q)&&f[q]._name===e)return f[q];return null};this.getDependents=function(){0===g.length&&(g=ORA.getDependents(d.prodId));return g};this.updateDependents=function(){g=ORA.getDependents(d.prodId)};
this.getExecuteState=function(){return this.executeState};this.hasMetDeps=function(){for(var e in f)if(f.hasOwnProperty(e)&&""!==e&&!0!==f[e]._met)if(k[e].getExecuteState()===f[e]._state)f[e]._met=!0;else return!1;return!0};this.updateDependencyState=function(e,q){var n=d.getDependency(e);null!==n&&n._state===q&&(n._met=!0)};this._startTimer=function(e){this.timer?h.Debug.info("LOADER:  "+this.prodId+" timer already started, using current timer."):(h.Debug.debug("LOADER:  starting timer for "+d.prodId),
this.timer=window.setTimeout(function(){h.Debug.error("LOADER:  "+d.prodId+"module timer expired calling Abort","015");h.fireEvent(new ORA.Event(d.prodId+"_"+ORA.Event.TIMER_EXPIRE,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(d.prodId+"_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS))},e),this.startTime=new Date,h.Debug.info("LOADER:  "+this.prodId+" timer started ["+this.startTime+"]."))};this._clearTimer=function(){this.stopTime=new Date;this.timer&&(clearTimeout(this.timer),this.timer=
null);h.Debug.info("LOADER:  "+this.prodId+" timer cleared ["+this.stopTime+"]")};this.tryExecPostload=function(){var e=d.getExecuteState()===x.READY,q=d.hasMetDeps(),n=void 0!==d.plugin[ORA.Event.POSTLOAD];if(q&&e&&n)return h.Debug.debug("setExecuteState:  "+d.prodId+" has met all dependencies \x26\x26 ready, running postload"),d.plugin[ORA.Event.POSTLOAD](),!0;if(q&&e)return ORA.Debug.superfine(d.prodId+", has no postLoad section"),!0;ORA.Debug.superfine(d.prodId+", did not meet postload exec conditionals");
return!1}};x.WAITING="waiting";x.DOWNLOADING="downloading";x.READY="ready";x.RUNNING="running";x.ABORTED="aborted";this.registerPlugin=function(a,b){k[a.ProductName]=new x(a.ProductName,a,b);k[a.ProductName].executeState=x.WAITING;ORA.hasVal(a.prototype.abort)&&ORA.addEventHandler(a.ProductName+"_"+ORA.Event.LOADER_MODULE_ABORT,a.prototype.abort);if(ORA.hasVal(a.prototype.oraConfigObj)&&ORA.hasVal(a.prototype.oraConfigObj.s_dependencies))for(var c=a.prototype.oraConfigObj.s_dependencies.split(","),
d=0;d<c.length;d++){var f=c[d].split(":");k[a.ProductName].putDependency(new T(f[0],f[1]))}for(var g in k)k.hasOwnProperty(g)&&k[g].updateDependents();a.prototype&&a.prototype.oraConfigObj&&a.prototype.oraConfigObj.s_useTrackingPipeline&&!0===a.prototype.oraConfigObj.s_useTrackingPipeline&&(k[a.ProductName].useTrackingPipeline=!0,c=a.prototype.oraConfigObj,ORA.hasVal(c.s_pageTimeout)&&ORA.hasVal(c.s_TrackingPipelineTimeout)?k[a.ProductName].s_TrackingPipelineTimeout=Math.max(c.s_pageTimeout,c.s_TrackingPipelineTimeout):
ORA.hasVal(c.s_pageTimeout)?k[a.ProductName].s_TrackingPipelineTimeout=c.s_pageTimeout:ORA.hasVal(c.s_TrackingPipelineTimeout)&&(k[a.ProductName].s_TrackingPipelineTimeout=c.s_TrackingPipelineTimeout))};this.clearPlugins=function(){k={}};this.hasMetDeps=function(a){return k[a].hasMetDeps()};this.getDependents=function(a){var b=[],c;for(c in k)k.hasOwnProperty(c)&&null!==k[c].getDependency(a)&&b.push(c);return b};this.updateDependencies=function(a,b){if(!a||!k[a])return null;if(!b)return k[a].clearDependencies(),
null;var c=b.split(",");if(!c||0===c.length)return null;k[a].clearDependencies();for(var d=0;d<c.length;d++){var f=c[d].split(":");if(2===f.length)k[a].putDependency(new T(f[0],f[1]));else break}return null};var U=function(a){var b=k[a];if(b.tryExecPostload()){b.executeState="running";a=b.getDependents(a);for(var c in a)a.hasOwnProperty(c)&&U(a[c])}};this.setExecuteState=function(a,b){if(b===ORA.Event.LOADER_MODULE_ABORT)k[a].executeState=x.ABORTED;else if(h.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT){k[a].executeState=
b;h.Debug.trace("setExecuteState:  "+a+" to "+b);var c=k[a].getDependents(),d;for(d in c)c.hasOwnProperty(d)&&k.hasOwnProperty(c[d])&&k[c[d]].updateDependencyState(a,b);U(a)}};this.getExecuteState=function(a){return ORA.hasVal(k[a])?k[a].executeState===x.ABORTED?ORA.Event.LOADER_MODULE_ABORT:k[a].executeState:null};this.isDependency=function(a){for(var b in k)if(k.hasOwnProperty(b)&&null!==k[b].getDependency(a))return h.Debug.trace("isDependency:  "+a+" is dependency of "+b),!0;h.Debug.trace("isDependency:  "+
a+" is not a dependency of any product");return!1};this.getTrackingPipelineProducts=function(){var a=[],b;for(b in k)if(k.hasOwnProperty(b)&&k[b].useTrackingPipeline){var c={};c.name=b;k[b].s_TrackingPipelineTimeout&&(c.timeout=k[b].s_TrackingPipelineTimeout);a.push(c)}return a};this.getContextUrl=function(a,b){return"//d.oracleinfinity.io/infy/acs/account/wh3g12c3gg/js/oracle/"+a+"-"+b+".js"};this.getProduct=function(a){for(var b in k)if(k.hasOwnProperty(b)&&a===k[b].prodId)return k[b];return null};
this.isProductEnabled=function(a){a+="Module";return ORA[a]&&ORA[a].prototype.oraConfigObj?void 0===ORA[a].prototype.oraConfigObj.enabled?!0:ORA[a].prototype.oraConfigObj.enabled:!1};this.isReady=function(){return P};this.isLoaded=function(){return K};this.addDOMEvent=function(a,b,c){try{return a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):eval("elm."+b+"\x3dfunc;"),0}catch(d){return-1}};this.removeDOMEvent=function(a,b,c){try{return a.removeEventListener?a.removeEventListener(b,
c,!1):a.detachEvent&&a.detachEvent("on"+b,c),0}catch(d){return-1}};this.getSafeEventName=function(a,b){var c=b.substr(0,2);if(a.addEventListener){if("on"===c)return b.substring(2)}else if(a.attachEvent&&"on"!==c)return"on"+b;return b};var da=function(){"complete"!==document.readyState&&"undefined"!==typeof document.readyState||D();document.addEventListener("DOMContentLoaded",function(){document.removeEventListener("DOMContentLoaded",arguments.callee,!1);D()},!1);if(/WebKit|Opera/i.test(navigator.userAgent))var a=
setInterval(function(){/loaded|complete/.test(document.readyState)&&(clearInterval(a),D())},10)},ea=function(){"complete"!==document.readyState&&"loading"!==document.readyState||D();document.attachEvent("onreadystatechange",function(){if("complete"===document.readyState||"loading"===document.readyState)document.detachEvent("onreadystatechange",arguments.callee),D()})},fa=function(){try{document.addEventListener&&da(),document.attachEvent&&ea(),window.addEventListener?window.addEventListener("load",
function(){window.removeEventListener("load",arguments.callee,!1);D()},!1):window.attachEvent&&window.attachEvent("onload",function(){window.detachEvent("onload",arguments.callee,!1);D()}),K?L():window.addEventListener?window.addEventListener("load",function(){window.removeEventListener("load",arguments.callee,!1);L()},!1):window.attachEvent&&window.attachEvent("onload",function(){window.detachEvent("onload",arguments.callee,!1);L()})}catch(a){D(),L()}};h.Debug=new h._Debug;var G=this.parseQueryString(t);
h.hasVal(G)&&h.hasVal(G["_ora.debug"])&&h.Debug.setDebugLevel(G["_ora.debug"]);var H=function(a){var b={};a=a.split(/[;,]/);for(var c in a)if(a.hasOwnProperty(c)){var d=a[c].split(":");b[d[0]]=d[1]}return b},A=function(){var a=R("_ora.context");var b=R("_ora.config");a=a||b||null;b=S("_ora.context");var c=S("_ora.config");b=b||c||null;c=G&&(G["_ora.context"]||G["_ora.config"]||null);for(var d=document.getElementsByTagName("SCRIPT"),f,g=/_ora\.context=([^&]*)|_ora\.config=([^&]*)/g,e=0;e<d.length&&
!f;e++)d[e].src&&/odc\.js\?/.test(d[e].src)&&(f=g.exec(d[e].src));if(null!==c)return H(c);if("undefined"!==typeof a&&null!==a)return H(a);if("undefined"!==typeof b&&null!==b)return H(b);if(f&&2<f.length)return void 0!==f[2]?H(f[2]):void 0!==f[1]?H(f[1]):H(f[0])}();if("undefined"!==typeof A){h.Debug.info("LOADER:  Found one or more context(s)");for(var Q in A)A.hasOwnProperty(Q)&&h.Debug.trace('LOADER:  triggers have set contextTriggerMap "'+Q+'":"'+A[Q]+'"')}var N=function(a){return"undefined"!==
typeof A&&"undefined"!==typeof k[a].configName&&"undefined"!==typeof A[a]&&A[a]===k[a].configName?(h.Debug.trace('LOADER:  context "'+k[a].configName+'" triggered for '+a),!0):"undefined"===typeof A||"undefined"===typeof A[a]?(h.Debug.trace("LOADER:  published context triggered for "+a),!0):!1},J=function(a){h.Debug.error("Loader Error: "+a,"016")};h.Debug.info("LOADER:  Version "+[v.major,v.minor,v.inc].join("."));this.addEventHandler(this.Event.PREINIT,function(){var a="unknown";try{for(a in k){var b;
if(b=k.hasOwnProperty(a)){var c=a;b=ORA.hasVal(k[c].plugin)&&ORA.hasVal(k[c].plugin[ORA.Event.PREINIT])}b&&N(a)&&ORA.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT&&(c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _preinit phase start',h.Debug.trace(c),k[a].plugin[ORA.Event.PREINIT](),c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _preinit phase complete',h.Debug.trace(c))}}catch(d){ORA.abortModuleHelper(a,d)}},function(){J("preinit fail")});this.addEventHandler(this.Event.INIT,
function(){var a="unknown";try{for(a in k){var b;if(b=k.hasOwnProperty(a)){var c=a;b=ORA.hasVal(k[c].plugin)&&ORA.hasVal(k[c].plugin[ORA.Event.INIT])}b&&N(a)&&ORA.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT&&(c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _init phase start',h.Debug.trace(c),k[a].plugin[ORA.Event.INIT](),c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _init phase complete',h.Debug.trace(c))}}catch(d){ORA.abortModuleHelper(a,d)}},
function(){J("init fail")});this.addEventHandler(this.Event.PRELOAD,function(){var a="unknown";try{for(a in k){var b;if(b=k.hasOwnProperty(a)){var c=a;b=ORA.hasVal(k[c].plugin)&&ORA.hasVal(k[c].plugin[ORA.Event.PRELOAD])&&ORA.hasVal(k[c].plugin.oraConfigObj)&&!0===k[c].plugin.oraConfigObj.doLoad}b&&N(a)&&ORA.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT&&(c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _preload phase start',h.Debug.trace(c),k[a].plugin[ORA.Event.PRELOAD](),
c='LOADER:  product "'+a+'" with context name "',c+=k[a].configName+'" _preload phase complete',h.Debug.trace(c))}}catch(d){ORA.abortModuleHelper(a,d)}},function(){J("preload fail")});this.addEventHandler(this.Event.LOAD,function(){var a="unknown";try{var b=function(f){return function(){ORA.Debug.debug(f+" downloaded successfully")}},c=function(f){f+="Module";return ORA[f]&&ORA[f].prototype.oraConfigObj&&ORA[f].prototype.oraConfigObj.loadPriority?ORA[f].prototype.oraConfigObj.loadPriority:0},d=function(f){var g;
if(g=k.hasOwnProperty(f))g=ORA.hasVal(k[f].plugin)&&ORA.hasVal(k[f].plugin[ORA.Event.LOAD])&&ORA.hasVal(k[f].plugin.oraConfigObj)&&!0===k[f].plugin.oraConfigObj.doLoad;g&&N(f)&&ORA.getExecuteState(f)!==ORA.Event.LOADER_MODULE_ABORT&&(ORA.setExecuteState(f,x.DOWNLOADING),g='LOADER:  product "'+f+'" with context name "'+(k[f].configName+'" _load phase start'),h.Debug.trace(g),k[f].plugin[ORA.Event.LOAD](b(f)),g='LOADER:  product "'+f+'" with context name "'+(k[f].configName+'" _load phase complete'),
h.Debug.trace(g))};for(a in k)k.hasOwnProperty(a)&&c(a)&&d(a);for(a in k)k.hasOwnProperty(a)&&!c(a)&&d(a)}catch(f){ORA.abortModuleHelper(a,f)}},function(){J("load fail")});this.addEventHandler(this.Event.LOADER_ABORT,function(){var a="unknown";B=!0;h.Debug.error("Loader global abort event","017");try{for(a in k)k.hasOwnProperty(a)&&ORA.hasVal(k[a].plugin)&&!0===k[a].plugin.oraConfigObj.doLoad&&(ORA.fireEvent(new ORA.Event(a+"_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS),!1,!0),ORA.setExecuteState(a,
ORA.Event.LOADER_MODULE_ABORT),ORA.clearTimer(a),ORA.Debug.error("Aborting product: "+a,"018"))}catch(b){ORA.abortModuleHelper(a,b)}},function(){J("abort fail")});var V=[];this.start=function(){var a=function(){h.fireEvent(new ORA.Event(ORA.Event.PREINIT,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(ORA.Event.INIT,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(ORA.Event.PRELOAD,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(ORA.Event.LOAD,ORA.Event.STATUS_SUCCESS));h.Debug.debug("LOADER:  Synchronous functionality has finished firing")},
b=function(){for(var c in A)if(A.hasOwnProperty(c)){var d=h.getContextUrl(c,A[c]);"undefined"!==typeof d&&(h.Debug.debug("LOADER:  adding "+d+" to download"),V.push(d))}};try{fa(),ORA.hasVal(A)?(h.Debug.debug("LOADER:  contextTriggerMap contains contexts"),b(),h.downloadLibs("head",a,0,!0,V)):a()}catch(c){h.fireEvent(new ORA.Event(ORA.Event.LOADER_ABORT,ORA.Event.STATUS_SUCCESS))}};this.productReady=function(a,b,c){var d=k[a];a=c||a+"_product_ready";if(d&&d.hasMetDeps()&&(d.executeState===x.READY||
d.executeState===x.RUNNING))try{b()}catch(f){ORA.Debug.debug("User supplied product ready callback failed "+f.message)}else d?(ORA.addEventHandler(a,b),ORA.Debug.debug("attached listener for "+a)):(ORA.Debug.debug("product was not found attaching to "+a),ORA.addEventHandler(a,b,null,!0))};this.productReady.push=function(a){ORA.productReady.apply(this,a);ORA.Debug.debug("productReady pushing function for "+a[0],"LOADER")};h.Debug.debug("ORA object created","LOADER");h.Debug.info('To dump config params use: "ORA.Debug.dumpParams()"');
h.Debug.info('To check the mode use: "ORA.Debug.checkMode(false)" - Use true if you wish to reset the mode.')}var l=function(t){var r=[];try{for(;0<t.length;)r=t.shift(),ORA.Debug.debug("productReady queue found when loading for "+r[0],"LOADER"),ORA.productReady.apply(this,r)}catch(v){ORA.Debug.debug("Error processing ORA.productReady queue "+v.message,"LOADER")}};if("undefined"===typeof ORA||"undefined"!==typeof ORA&&!ORA.ready){var p=[];"undefined"!==typeof ORA&&ORA.productReady&&(p=ORA.productReady);
ORA=new m(window,window.document,window.navigator,window.location);l(p);ORA.ready=!0}else console.error("ORA global namespace already in use, Infinity not loaded/setup")})();
(function(){"undefined"!==typeof ORA&&!0===ORA.ready&&(!0===ORA.isInitCompleted?ORA.Debug.error("The tag is being loaded multiple times. Exiting second tag initialization request."):(ORA.isInitCompleted=!0,ORA.registerPlugin=ORA.registerPlugin,ORA.abortModuleHelper=ORA.abortModuleHelper,ORA.setLoaderConversionTimeoutDefault=ORA.setLoaderConversionTimeoutDefault,ORA.loaderConversionTimeoutDefault=ORA.loaderConversionTimeoutDefault,ORA.downloadLib=ORA.downloadLib,ORA.reset=ORA.reset,ORA.productLoadInit=
function(){ORA.analyticsModule=function(){};ORA.analyticsModule.prototype.oraConfigObj={s_disableSeed:!1,alwaysLoad:!0,enabled:!0,DNTBehavior:"honorDNT",skip_qp_no_equals:!0,s_dependencies:"common:running","hosted-plugins":{InfinityPlugin:{enable:!0,src:"https://www.oracle.com/asset/web/analytics/infinity_common.js",blockCollect:!1},infinity_click_tracking_ocom:{enable:!0,src:"https://www.oracle.com/asset/web/analytics/infinity_click_tracking_ocom.js",blockCollect:!1}},accountGuid:"wh3g12c3gg",tagId:"oracle",
cookieTypes:"firstpartyonly","ora-plugins":{evtTrack:{enable:!0,trackSocial:!0,standardEvents:{anchor:!1,onsite:!1,offsite:!0,rightclick:!1,download:!0,javascript:!1,scrollTracking:!0},downloadtypes:"xls, doc, pdf, txt, csv, zip, docx, xlsx, rar, gzip, pptx"},yt:{poll:!0,pctInc:25,seek:!0,pause:!0,load:!1,cued:!1,loadMeta:!0,beacon:!0,mode:"auto",quartile:!0,buffering:!1,loadAPI:!1,enable:!0,legacy:!1,bins:15,beaconRate:60,volume:!1},heatmap:{enable:!0,maxymiserEnable:!0},cookieCutter:{readCookies:[{cookie:{TEST:"ora.cook_a"},
options:{persist:!0}},{cookie:{ORA_FPC:{id:"ora.c_id",ss:"ora.c_ss",lv:"ora.c_lv"}},options:{parseOn:":",parseLv:"\x3d"}},{cookie:{ELOQUA:{GUID:"ora.elq.vid",FPCVISITED:"ora.eloqua_flag"}},options:{parseOn:"\x26",persist:!0}},{cookie:{utag_main:{_ss:"ora.u_ss",_st:"ora.u_st",v_id:"ora.u_vid",_sn:"ora.u_sn",ses_id:"ora.u_ses_id"}},options:{parseOn:"$",parseLv:":",persist:!1}},{cookie:{WTPERSIST:{elqCid:"ora.elq.cid"}},options:{parseOn:"\x26",parseLv:"\x3d"}}],enable:!0},pp:{enable:!0,lowerCaseValues:!0,
defPrefix:"DCSext",params:"dcsvid infy riid rid customer_id elqCID elqCid elq_cid elq_mid product".split(" "),useMostRecent:!0,cookieName:"WTPERSIST",cookieDays:365,priority:100},crossDomain:{enable:!1,encode:!1,ignoreOnsiteDoms:!1,guard:"~",denyListSelector:"localhost",addIdTreatment:"auto",allowListSelector:"A",blockCollect:!0},cg:{enable:!0,cgDefs:"wt.cg_l1 wt.cg_l2 wt.cg_l3 wt.cg_l4 wt.cg_l5 wt.cg_l6 wt.cg_l7 wt.cg_l8 wt.cg_l9 wt.cg_l10".split(" "),blockCollect:!0},fragment:{virtualPageView:!1,
addAnchorName:"name",applyClickEventOnly:!1,prefix:"anchor",blockCollect:!0,virtialDl:26,paramHandeling:"addPrefix"},bc:{enable:!0,poll:!1,pctInc:25,beraconType:"auto",seek:!0,pollRate:250,load:!1,cued:!1,loadMeta:!1,maxBinds:10,postMessage:!1,fixed:!1,playerId:"div[id^\x3d'bcvid']:not([id$\x3d'_api']):not([id*\x3d'_component']):not(video)",quartile:!0,buffering:!1,beaconCurve:{300:30,60:10,600:60,130:30,420:45,1800:150},pause:!0,screenMode:!1,beacon:!0,bins:15,beaconRate:60,metaTags:!0,volume:!1}},
timezone:0,defaultCollectionServer:"dc.oracleinfinity.io",s_useTrackingPipeline:!0,s_waitForSetClientId:!1,libUrl:"//d.oracleinfinity.io/infy/acs/account/wh3g12c3gg/js/oracle/analytics-production/analytics.js",secureCookie:!1,FPCConfig:{domain:".oracle.com",sessionOnly:!1,autoTLD:!1},destinations:[{accountGuid:"wh3g12c3gg"}],s_TrackingPipelineTimeout:4E3};typeof ORA.analyticsModule.prototype.oraConfigObj.enabled&&!1===ORA.analyticsModule.prototype.oraConfigObj.enabled?ORA.Debug.debug("analytics  module disabled - exiting module setup"):
(ORA.analyticsModule.prototype.preinit=function(){try{ORA.Debug.debug("PREINIT: Executing Preinit script")}catch(m){ORA.abortModuleHelper("analytics",m)}},ORA.analyticsModule.prototype.init=function(){try{this.oraConfigObj.key="value ",void 0===this.oraConfigObj.doLoad&&(this.oraConfigObj.doLoad=!0),this.oraConfigObj.doLoad=this.oraConfigObj.doLoad||this.oraConfigObj.alwaysLoad}catch(m){ORA.abortModuleHelper("analytics",m)}},ORA.analyticsModule.prototype.preload=function(){try{var m=0;ORA.analyticsModule.prototype.oraConfigObj.s_conversionTimeout&&
(m=ORA.analyticsModule.prototype.oraConfigObj.s_conversionTimeout);ORA.setLoaderConversionTimeoutDefault(Math.max(m,ORA.loaderConversionTimeoutDefault()));ORA.Debug.debug("PRELOAD:  Executing preload script")}catch(l){ORA.abortModuleHelper("analytics",l)}},ORA.analyticsModule.prototype.load=function(m){try{ORA.Debug.debug("LOAD:  Executing load phase"),(results=ORA.parseQueryString(location.search)&&ORA.parseQueryString(location.search).xd_co_f)&&(document.cookie="FA_InAppTrack\x3dtrue; expires\x3d0; path\x3d/; domain\x3d.oracle.com"),
ORA.productReady.push(["analytics",function(){if(results=ORA.parseQueryString(location.search)&&ORA.parseQueryString(location.search).xd_co_f){var l=ORA.analytics.dcsRef,p=l.FPCConfig.expireDate||new Date((new Date).getTime()+63113851500),t="";l.FPCConfig.sessionOnly||(t="; expires\x3d"+p.toGMTString());ORA.analytics.setCookie(l.FPCConfig.name||"ORA_FPC",{id:results},""===l.FPCConfig.domain?t+"; path\x3d/":t+"; path\x3d/; domain\x3d"+l.FPCConfig.domain)}document.cookie.match("FA_InAppTrack\x3dtrue")&&
ORA.analytics.dcsRef.destinations.push({accountGuid:"3de8bca273ab47a936d9deaa5516326b",collectionServer:"dc.oracleinfinity.io",endpoint:"https://dc.oracleinfinity.io/3de8bca273ab47a936d9deaa5516326b/dcs.gif"})}]),ORA.productReady.push(["analytics",function(){var l=[{paramSrc:"source",paramTarget:"ora.mc_l",skipFirstEmpty:!0,lowerCase:!1}];ORA.analytics.addMutation("campaign_split",function(p){try{var t=p.payload;for(p=0;p<=l.length;p++)if(void 0!==t[l[p].paramSrc])for(var r,v=String(t[l[p].paramSrc]).split(l[p].seperator||
":"),h=0;0<v.length;)r=v.shift(),l[p].lowerCase&&(r=r.toLowerCase()),(void 0===r||""===r)&&0===h&&!0===l[p].skipFirstEmpty||(""===r&&(r="undefined"),t[l[p].paramTarget+h.toString()]=r),h++}catch(B){ORA.Debug.debug("campaign_split mutation error:"+B.message)}});ORA.analytics.addMutation("lowercase_gcm_uid",function(p){try{p.payload&&p.payload["wt.gcm_uid"]&&(p.payload["wt.gcm_uid"]=p.payload["wt.gcm_uid"].toLowerCase())}catch(t){ORA.Debug.debug("lowercase_gcm_uid mutation error:"+t.message)}})},"_ora_plugins_init"]),
ORA.downloadLib("head",m,function(){ORA.fireEvent(new ORA.Event("analytics_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS))},0,!0,this.oraConfigObj.libUrl)}catch(l){ORA.abortModuleHelper("analytics",l)}},ORA.analyticsModule.prototype.postload=function(){ORA.Debug.debug("POSTLOAD:  Executing postload analytics complete");try{ORA.Debug.info("LOADER:  ORA.analyticsModule.prototype: postload"),ORA.analytics.setup(ORA.analyticsModule.prototype.oraConfigObj)}catch(m){ORA.abortModuleHelper("analytics",
m)}},ORA.analyticsModule.prototype.abort=function(){try{ORA.Debug.debug("ABORT:  Executing analyticsModule abort")}catch(m){ORA.abortModuleHelper("analytics",m)}});ORA.analyticsModule.ProductName="analytics";ORA.registerPlugin(ORA.analyticsModule,"production")},function(){var m=!0;ORA.sizzleModule=function(){};ORA.sizzleModule.prototype.oraConfigObj={libUrl:"//d.oracleinfinity.io/infy/acs/common/js/lib/sizzle.min.js",doLoad:!0,s_dependencies:""};ORA.sizzleModule.setLoaded=function(l){m=l};ORA.sizzleModule.getLoaded=
function(){return m};ORA.sizzleModule.prototype.load=function(l){try{ORA.updateDependencies("sizzle",this.oraConfigObj.s_dependencies),"undefined"===typeof JSON&&ORA.isDependency("sizzle")?(ORA.Debug.debug("Sizzle not detected"),ORA.sizzleModule.setLoaded(!1),ORA.downloadLib("head",l,function(){ORA.abortModuleHelper("sizzle","failed to download sizzle")},0,!0,this.oraConfigObj.libUrl)):(ORA.sizzleModule.setLoaded(!0),ORA.setExecuteState("sizzle","ready"))}catch(p){ORA.abortModuleHelper("sizzle",p)}};
ORA.sizzleModule.prototype.postload=function(){};ORA.sizzleModule.ProductName="sizzle";ORA.registerPlugin(ORA.sizzleModule,"default")}(),function(){var m=!0;ORA.jsonModule=function(){};ORA.jsonModule.prototype.oraConfigObj={libUrl:"//d.oracleinfinity.io/infy/acs/common/js/lib/json2.js",doLoad:!0,s_dependencies:""};ORA.jsonModule.setLoaded=function(l){m=l};ORA.jsonModule.getLoaded=function(){return m};ORA.jsonModule.prototype.load=function(l){try{ORA.updateDependencies("json",this.oraConfigObj.s_dependencies),
"undefined"===typeof JSON&&ORA.isDependency("json")?(ORA.Debug.debug("JSON not detected"),ORA.jsonModule.setLoaded(!1),ORA.downloadLib("head",l,function(){ORA.abortModuleHelper("json","failed to download json");ORA.abortModuleHelper("analytics","failed to download json")},0,!0,this.oraConfigObj.libUrl)):(ORA.jsonModule.setLoaded(!0),ORA.setExecuteState("json","ready"))}catch(p){ORA.abortModuleHelper("analytics",p)}};ORA.jsonModule.prototype.postload=function(){};ORA.jsonModule.ProductName="json";
ORA.registerPlugin(ORA.jsonModule,"default")}(),function(){ORA.Event.BLUEKAI_DATA_READY="bluekai_data_ready";var m={},l=function(){};"undefined"===typeof Array.isArray&&(Array.isArray=function(h){return"[object Array]"===Object.prototype.toString.call(h)});var p=function(h,B){var C=B||"",z;for(z in h)h.hasOwnProperty(z)&&(Array.isArray(h[z])?m["ora."+C+"_"+z]=h[z].join(";"):"object"===typeof h[z]?p(h[z],C+"_"+z):m["ora."+C+"_"+z]=h[z]);return null},t=function(h){var B=[],C;for(C in h)h.hasOwnProperty(C)&&
(B.push(String(C)),B.push(encodeURIComponent(h[C])));return B.join(",")},r=function(h){h&&h.data&&"bluekai"===h.data.source&&(p(h.data,"odc"),"undefined"!==typeof ORA.setCookie?ORA.setCookie("bluekai_uid_plugin",t(m),"; path\x3d/"):document.cookie="bluekai_uid_plugin\x3d"+t(m)+"; path\x3d/");l()},v=function(){window.addEventListener?window.addEventListener("message",r,!1):ORA.Debug.debug("bluekai reguires addEventListener support","LOADER-bluekai")};l=function(){ORA.Debug.debug("Removing postMessage lister for bluekai data",
"ANA-bluekai_uid_plugin");window.removeEventListener?window.removeEventListener("message",r):window.removeEvent?window.removeEvent("onmessage",r):ORA.Debug.debug("Browser does not support Removing messageListeners - exiting","ANA-bluekai_uid_plugin");ORA.fireEvent(new ORA.Event(ORA.Event.BLUEKAI_DATA_READY,ORA.Event.STATUS_SUCCESS))};ORA&&ORA.fireEvent&&ORA.Debug&&setTimeout(v,1);window.ORA.bkLoader=v}(),function(){ORA.commonModule=function(){};ORA.Event.COMMON_LOAD_COMPLETE="common_load_complete";
ORA.Event.COMMON_ORA_PLUGINMGR_READY="common_ora_pluginmgr_ready";ORA.Event.COMMON_HOSTED_PLUGINMGR_READY="common_hosted_pluginmgr_ready";ORA.Event.COMMON_TRACKING_FLUSH="common_tracking_flush";ORA.Event.COMMON_COM_EXEC_REQ="common_com_exec_req";ORA.Event.COMMON_BEFORE_GETID="common_before_getid";ORA.Event.COMMON_GETID="common_get_id";ORA.Event.COMMON_PRODUCT_READY="common_product_ready";ORA.commonModule.prototype.oraConfigObj={libUrl:"//d.oracleinfinity.io/infy/acs/common/js/1.3.49/common.js",doLoad:!0,
s_dependencies:"json:running"};ORA.commonModule.prototype.load=function(m){try{(!ORA.hasVal(ORA.common)||ORA.hasVal(ORA.common)&&!ORA.hasVal(ORA.common.TrackingPipeline))&&ORA.isDependency("common")&&ORA.downloadLib("head",m,function(){ORA.fireEvent(new ORA.Event("common"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS))},0,!0,this.oraConfigObj.libUrl)}catch(l){ORA.abortModuleHelper("common",l)}};ORA.commonModule.prototype.postload=function(){ORA.common.setup()};ORA.commonModule.ProductName=
"common";ORA.registerPlugin(ORA.commonModule,"default")}(),function(){ORA.Event.ANA_LOAD_COMPLETE="analytics_load_complete";ORA.Event.ANA_ORA_PLUGINS_LOADED="analytics_ora_plugins_loaded";ORA.Event.ANA_HOSTED_PLUGINS_LOADED="analytics_hosted_plugins_loaded";ORA.Event.ANA_ORA_PLUGINS_INIT="analytics_ora_plugins_init";ORA.Event.ANA_HOSTED_PLUGINS_INIT="analytics_hosted_plugins_init";ORA.Event.ANA_DCS_SETUP="analytics_dcs_setup";ORA.Event.ANA_PRODUCT_READY="analytics_product_ready";ORA.Event.ANA_SETUP_COMPLETE=
"analytics_setup_complete";ORA.Event.ANA_BEFORE_PAGE_ANALYSIS="analytics_before_page_analysis";ORA.Event.ANA_AFTER_PAGE_ANALYSIS="analytics_after_page_analysis";ORA.Event.ANA_BEFORE_GETID="analytics_before_getid";ORA.Event.ANA_AFTER_GETID="analytics_after_getid";ORA.Event.ANA_PV_MUTATE="analytics_pv_mutate";ORA.Event.ANA_DATA_SEND="analytics_data_send";ORA.Event.LOADER_CLICK="loader_click";ORA.Event.LOADER_PRE_EXECUTE="loader_pre_execute";ORA.Event.LOADER_EXECUTE="loader_execute";ORA.Event.LOADER_RESET=
"loader_reset";ORA.Event.LOADER_COLLECT="loader_collect";ORA.Event.LOADER_VIEW="loader_view";ORA.getContextName=function(){return ORA.getProduct("analytics")&&ORA.getProduct("analytics").configName||""};ORA.getConfigName=function(){return ORA.getProduct("analytics")&&ORA.getProduct("analytics").configName||""};var m=function(l,p){ORA.fireEvent(new ORA.Event(l,ORA.Event.STATUS_SUCCESS,null,p),null,null,!0)};ORA.collect=function(l){m(ORA.Event.LOADER_COLLECT,l);return!0};ORA.view=function(l){m(ORA.Event.LOADER_VIEW,
l);return!0};ORA.click=ORA.sendEvent=function(l){m(ORA.Event.LOADER_CLICK,l);return!0};ORA.regPlugin=function(l,p,t){var r=function(){ORA.Debug.debug("regPlugin - call of deferred register of "+l,"LOADER");void 0===ORA.analytics.plugins[l]?(ORA.Debug.debug("Registering init for "+l),ORA.common.pluginMgr._regPlugin(l,p,t)):ORA.analytics.plugins[l]&&ORA.analytics.plugins[l].src?(ORA.analytics.plugins[l].loaded=!0,ORA.common.hostedPluginMgr._regPlugin(l,p,t,"hosted-plugins")):ORA.common.pluginMgr._regPlugin(l,
p,t)};ORA.common&&ORA.common.pluginMgr&&ORA.common.pluginMgr.isReady&&!0===ORA.common.pluginMgr.isReady()?(ORA.Debug.debug("ORA.common.pluginMgr exists so register is possible"),r()):(ORA.Debug.debug("regPlugin - deferred register of "+l,"LOADER"),ORA.analytics.plugins[l]&&ORA.analytics.plugins[l].src?ORA.addEventHandler(ORA.Event.COMMON_HOSTED_PLUGINMGR_READY,r,null,!0):ORA.addEventHandler(ORA.Event.COMMON_ORA_PLUGINMGR_READY,r,null,!0))};ORA.setUserParameter=function(l,p){if("string"===typeof l&&
"string"===typeof p){var t={};t[l]=p;return ORA.setUserParameters(t)}ORA.Debug.error("Invalid user parameters are passed. Either key or value passed is null.");return!1};ORA.setUserParameters=function(l){try{if("object"===typeof l&&0<Object.keys(l).length){var p={};Object.keys(l).forEach(function(t){if("string"===typeof l[t]||"number"===typeof l[t]||"boolean"===typeof l[t])p["user."+t]=l[t];else return ORA.Debug.error("Invalid value type in the user parameter json object for key"+t+"Only string values are accepted."),
!1});p["wt.dl"]="51";p.dcsuri=window.location.pathname;p["wt.ev"]="userParams";p["wt.sys"]="userParams";return ORA.click({data:p})}ORA.Debug.error("Invalid user parameters are passed. The object passed is invalid or null.");return!1}catch(t){return ORA.Debug.error("Invalid user parameters are passed. The object passed is invalid or null."),!1}}}(),function(){ORA.responsysModule=function(){};ORA.responsysModule.prototype.oraConfigObj={doLoad:!0,s_dependencies:"",config:{cookie_name:"responsys_cookie_default",
fallback_cookie_domain_level:0,fallback_timeout:"2000",urlSuffix:"/pub/cc",responsysURL:"",additionalParms:"_pb_\x3dR\x26_tt_\x3dQ"}};ORA.responsysModule.prototype.moveAndToResp=function(m,l){for(var p in m.config)m.config.hasOwnProperty(p)&&""!==m.config[p]&&(l.config[p]=m.config[p])};ORA.responsysModule.prototype.validateSettings=function(m){m.config.responsysURL||(ORA.debug("missing required setting for responsysURL, disabling module","responsys"),m.enabled=!1)};ORA.responsysModule.prototype.postload=
function(){var m=function(){ORA.Debug.debug("responsysModule load pixel failed - fallback to standard cookie",ORA.responsysModule.ProductName);ORA.responsysModule.prototype.cookieFallback()},l=function(){ORA.Debug.debug("responsysModule load pixel success",ORA.responsysModule.ProductName)};try{if(this.responsysExists()){var p=this.prepareUrl()+this.removeParameterList(location.search,this.oraConfigObj.config.additionalParms);p+="\x26"+this.oraConfigObj.config.additionalParms+location.hash;this.responsysLoadPixel(p,
l,m,this.oraConfigObj.config.fallback_timeout);return!0}ORA.setExecuteState("responsysModule","ready")}catch(t){return ORA.Debug.debug("responsysModule load error "+t.message),!1}};ORA.responsysModule.prototype.load=function(){try{var m={};if(ORA.analyticsModule&&ORA.analyticsModule.prototype&&ORA.analyticsModule.prototype.oraConfigObj&&ORA.analyticsModule.prototype.oraConfigObj.responsys){var l=ORA.responsysModule.prototype.oraConfigObj;m=ORA.analyticsModule.prototype.oraConfigObj.responsys;m.doLoad&&
(l.doLoad=m.doLoad);m.s_dependencies&&(l.s_dependencies=m.s_dependencies);ORA.responsysModule.prototype.moveAndToResp(m,l);ORA.responsysModule.prototype.validateSettings(m)}void 0!==m.enabled&&m.enabled?(ORA.updateDependencies("responsysModule","analytics:downloading"),ORA.setExecuteState("responsysModule","ready")):ORA.debug("responsys module not enabled","responsys")}catch(p){ORA.Debug.debug("responsysModule load error "+p.message)}};ORA.responsysModule.prototype.responsysExists=function(m){m=ORA.parseQueryString(m);
return!!(m&&m._ri_&&m._ei_)};ORA.responsysModule.prototype.responsysLoadPixel=function(m,l,p,t){var r=new Image,v=!1;r.onload=function(){v||(v=!0,l(),ORA.Debug.debug("Responsys pixel loaded",ORA.responsysModule.ProductName))};r.onerror=function(){v||(v=!0,p(),ORA.Debug.debug("Responsys pixel load failed",ORA.responsysModule.ProductName))};window.setTimeout(function(){v&&1!==t||(v=!0,ORA.Debug.debug("Responsys pixel load failed",ORA.responsysModule.ProductName),p())},t);r.src=m};ORA.responsysModule.prototype.cookieFallback=
function(m){var l=ORA.parseQueryString(m),p=this.oraConfigObj.config;m=p.cookie_name;l="_ri_"+l._ri_+"\x26_ei_"+l._ei_;var t=location.hostname.split(".");p=p.fallback_cookie_domain_level;var r=new Date,v="";for(r.setTime(r.getTime()+63113851500);p;)t.shift(),p--;t.join(".")!==location.host&&(v=";domain\x3d"+t.join("."));t="; path\x3d/ ; expires\x3d "+r.toGMTString()+v;ORA.Debug.debug("Setting fallback cookie","responsysModule");ORA.setCookie(m,l,t)};ORA.responsysModule.prototype.removeParameter=function(m,
l){var p=m.split("?");if(2<=p.length){for(var t=encodeURIComponent(l)+"\x3d",r=p[1].split(/[&;]/g),v=r.length;0<v;)v--,-1!==r[v].lastIndexOf(t,0)&&r.splice(v,1);return 0<r.length?p[0]+r.join("\x26"):p[0]}return m};ORA.responsysModule.prototype.removeParameterList=function(m,l){for(var p=m,t=l.split("\x26"),r=0;r<t.length;r++){var v=t[r].split("\x3d");p=this.removeParameter(p,v[0])}return"?"+p};ORA.responsysModule.prototype.prepareUrl=function(){var m=this.oraConfigObj.config,l=m.responsysURL;m.urlBase&&
""!==m.urlBase&&(l=m.urlBase);return l+m.urlSuffix};ORA.responsysModule.ProductName="responsysModule";ORA.registerPlugin(ORA.responsysModule,"default")}(),ORA.productLoadInit(),ORA.start()))})();